/* ============================================================
   art/act1.js - ACT ONE. The castle, and the man who lived in
   it before he lost it.

   Everything here is drawn at 40x60 or bigger, two and a half
   times the pixels of the 24x36 sprite the rest of the game
   runs on, because Act One is played close up and the art has
   to hold at that distance. More shades per surface too: every
   mail plate gets a lit edge, the crown has gems, the cape has
   folds and the steel has a highlight.

   Frames are derived with ed(): a frame lists only the rows
   that move, so a walk cycle reads as four poses instead of
   two hundred and forty lines of near-identical rows.

   Same 64-colour palette and the same legend as art/actors.js,
   so this is not a different game from the rest of it.
   ============================================================ */
KD.art.act1 = (function () {
  const P = KD.PX;
  const C = {
    o: 'INK.0', p: 'INK.1', q: 'INK.2', P: 'INK.3',
    s: 'SKIN.0', S: 'SKIN.1', k: 'SKIN.2', K: 'SKIN.3',
    b: 'BONE.0', B: 'BONE.1', w: 'BONE.2', W: 'WHITE',
    g: 'GOLD.0', G: 'GOLD.1', y: 'GOLD.2', Y: 'GOLD.3',
    t: 'WATER.0', T: 'WATER.1', c: 'WATER.2', C: 'WATER.3',
    i: 'DEEP.0', d: 'DEEP.1', D: 'DEEP.2', e: 'DEEP.3', E: 'DEEP.4',
    n: 'SAND.0', N: 'SAND.1', m: 'SAND.2', M: 'SAND.3',
    r: 'CORAL.0', R: 'CORAL.1', x: 'CORAL.2', X: 'CORAL.3',
    f: 'KELP.0', F: 'KELP.1', '+': 'KELP.2', '*': 'KELP.3',
    u: 'RUST.0', U: 'RUST.1', v: 'RUST.2', V: 'RUST.3',
    h: 'STONE.0', H: 'STONE.1', j: 'STONE.2', J: 'STONE.3',
    z: 'ROT.0', Z: 'ROT.1', a: 'ROT.2', A: 'ROT.3',
    '#': 'BLOOD.0', $: 'BLOOD.1', '%': 'BLOOD.2', '&': 'BLOOD.3',
    1: 'WOOD.0', 2: 'WOOD.1', 3: 'WOOD.2', 4: 'WOOD.3',
    5: 'CLOTH.0', 6: 'CLOTH.1', 7: 'CLOTH.2', 8: 'CLOTH.3'
  };
  /* a frame is its base with a handful of rows swapped out */
  const ed = (base, ch) => { const o = base.slice(); for (const k in ch) o[k] = ch[k]; return o; };
  const A = (px, ax, ay) => ({ pal: C, ax: ax, ay: ay, px: px });
  /* 40x60, anchored between the boots */
  const K1 = (name, rows) => P.def(name, A(rows, 18, 60));


  /* ---- THE KING IN HIS PRIME ---- */
  function king() {
    const K = [
      '...........o..o..o..o..o................',
      '..........oYooYooYooYooYo......W..W..W..',
      '.........oGYYoYYoYYoYYoYYGo....Wb.Wb.Wb.',
      '.........oGYY#YYY#YYY#YYYGo....Wb.Wb.Wb.',
      '.........ogGGGGGGGGGGGGGGgo....Wb.Wb.Wb.',
      '..........omNNNNNNNNNNNNno.....Wb.Wb.Wb.',
      '.........omNNNNNNNNNNNNNNno....Wb.Wb.Wb.',
      '.........oNnKKKKKKKKKKKKnNo....Wb.Wb.Wb.',
      '.........oNnkKoooKKoooKknNo....Wb.Wb.Wb.',
      '.........oNnKKoWoKKKoWoKnNo....Wb.Wb.Wb.',
      '.........oNnKKqpqKKKqpqKnNo....Wb.Wb.Wb.',
      '.........oNnKKKKkkKKKKKKnNo....WWWWWWWW.',
      '.........oNnKKKoSkoKKKKKnNo....obbbbbbo.',
      '.........oNnnnnnnnnnnnnnnNo......gYYg...',
      '.........onNNNNoqqoNNNNno........oYYo...',
      '.........onNNNNNNNNNNNNno........gyyg...',
      '..........onNNNNNNNNNNno.........o32o...',
      '............onNNNNNNno...........o32o...',
      '..............okkkko.............o32o...',
      '........oo%$$oYyyyyyYo$$#oo......o32o...',
      '......oo%$$#jjoyyyyyojj%$$#oo....o32o...',
      '.....oo%$#Jjjjjjjjjjjjjjh%$#oo...o32o...',
      '....o%ojjjjjjjjjjjjjjjjjhhhho#o..o32o...',
      '...ooKkkSojJJJJJjjjjjjjjjoKkkSo..o32o...',
      '..o%oKkkSojjjjjjjhjjjjjjjoKkkSo..o32o...',
      '..ooKkkSohhhhYhhYhhYhhhhhhoKkkSo.o32o...',
      '.o%oKkkSojjjjYjjYjjYjjjjjhoKkkSo.o32o...',
      '.o%oKkkSojjjjYYYYYYYjjjjjhoKkkSo.o32o...',
      'o%#oKkkSoJhhhhhhYhhhhhhhhhoKkkSo.o32o...',
      'o%$#oSSSSojjjjjjYjjjjjjjjhoSSSSo.o32o...',
      'o%$$oYyyyojjjjjyYyjjjjjjhooYyyyo.o32o...',
      'o%#$oKkSooJhhhhhhhhhhhhhho.oKkSo.o32o...',
      'o%$#oKkSooJjjjjjjjjjjjjjho.oKkSo.o32o...',
      'o%$$#oKkSoJjjjjjjjjjjjjho...oKkSoo32o...',
      'o%#$$oKkSoYyyyyyyyyyyyyygo..oKkSoo32o...',
      'o%$#$oKkSoYyyyyo&&&oyyyygo...oKkSo11o...',
      'o%$$#oKkSoyggggggggggggggo...oKkSo11o...',
      'o%#$$oKkSoCcccccccccccccto...oKkSo32o...',
      '.o%$#oKkSoCcccccccccccccto...oKoKKKKo...',
      '.o%$$oKkSoCcccccYccccccto....oKoKkkKo...',
      '..o%#$okkoCcccccyccccccto.....okko32o...',
      '..o%$##o..oCcccccccccccto........o32o...',
      '...o%$##..oYyyyyyyyyyyyYo........o32o...',
      '...o%##o.oJjjjho...oJjjjho.......o32o...',
      '....o%#o.oJjjjho...oJjjjho.......o32o...',
      '.....o%#ooJjjjho...oJjjjho.......o32o...',
      '......o$ooJjjjho...oJjjjho.......o32o...',
      '.......o$oJjjjho...oJjjjho.......o32o...',
      '........oojhhhho...ojhhhho.......o32o...',
      '.........oJjjjho...oJjjjho.......o32o...',
      '.........oYYYYYo...oYYYYYo.......o32o...',
      '.........oJjjjho...oJjjjho.......o32o...',
      '.........oJjjjho...oJjjjho.......o32o...',
      '.........oJjjjho...oJjjjho.......o32o...',
      '.........oJjjjho...oJjjjho.......o32o...',
      '.........oJjjjho...oJjjjho.......o32o...',
      '.........oJjjjho...oJjjjho.......o32o...',
      '........oeDDDDDio.oeDDDDDio......o32o...',
      '........oeDDDDDio.oeDDDDDio......o32o...',
      '........ooooooooo.ooooooooo......gYYg...'
    ];
    K1('kp_idle0', K);
    const _kp_idle1 = [
      '........................................',
      '...........o..o..o..o..o.......W..W..W..',
      '..........oYooYooYooYooYo......Wb.Wb.Wb.',
      '.........oGYYoYYoYYoYYoYYGo....Wb.Wb.Wb.',
      '.........oGYY#YYY#YYY#YYYGo....Wb.Wb.Wb.',
      '.........ogGGGGGGGGGGGGGGgo....Wb.Wb.Wb.',
      '..........omNNNNNNNNNNNNno.....Wb.Wb.Wb.',
      '.........omNNNNNNNNNNNNNNno....Wb.Wb.Wb.',
      '.........oNnKKKKKKKKKKKKnNo....Wb.Wb.Wb.',
      '.........oNnkKoooKKoooKknNo....Wb.Wb.Wb.',
      '.........oNnKKqqqKKqqqKKnNo....Wb.Wb.Wb.',
      '.........oNnKKKKKKKKKKKKnNo....WWWWWWWW.',
      '.........oNnKKKKkkKKKKKKnNo....obbbbbbo.',
      '.........oNnKKKoSkoKKKKKnNo......gYYg...',
      '.........oNnnnnnnnnnnnnnnNo......oYYo...',
      '.........onNNNNoqqoNNNNno........gyyg...',
      '..........onNNNNNNNNNNNNno.......o32o...',
      '...........onNNNNNNNNNNno........o32o...',
      '.............onNNNNNNno..........o32o...',
      '..............okkkko.............o32o...',
      '.......o%o%$$oYyyyyyYo$$#o.......o32o...',
      '.....o%o%$$#jjoyyyyyojj%$$#o.....o32o...',
      '....o%o%$#Jjjjjjjjjjjjjjh%$#o....o32o...',
      '...o%#ojjjjjjjjjjjjjjjjjhhhhoo...o32o...',
      '..o%oKkkSojJJJJJjjjjjjjjjoKkkSo..o32o...',
      '.o%$oKkkSojjjjjjjhjjjjjjjoKkkSo..o32o...',
      '.o%oKkkSohhhhYhhYhhYhhhhhhoKkkSo.o32o...',
      'o%$oKkkSojjjjYjjYjjYjjjjjhoKkkSo.o32o...',
      'o%$oKkkSojjjjYYYYYYYjjjjjhoKkkSo.o32o...',
      'o%#oKkkSoJhhhhhhYhhhhhhhhhoKkkSo.o32o...',
      'o%$#oSSSSojjjjjjYjjjjjjjjhoSSSSo.o32o...',
      'o%$$oYyyyojjjjjyYyjjjjjjhooYyyyo.o32o...',
      'o%#$oKkSooJhhhhhhhhhhhhhho.oKkSo.o32o...',
      'o%$#oKkSooJjjjjjjjjjjjjjho.oKkSo.o32o...',
      'o%$$#oKkSoJjjjjjjjjjjjjho...oKkSoo32o...',
      'o%#$$oKkSoYyyyyyyyyyyyyygo..oKkSoo11o...',
      'o%$#$oKkSoYyyyyo&&&oyyyygo...oKkSo11o...',
      'o%$$#oKkSoyggggggggggggggo...oKkSo32o...',
      'o%#$$oKkSoCcccccccccccccto...oKoKKKKo...',
      'o%$#$oKkSoCcccccccccccccto...oKoKkkKo...',
      'o%$$#oKkSoCcccccYccccccto....oKkSo32o...',
      '.o%#$#okkoCcccccyccccccto.....okko32o...',
      '.o%$##o...oCcccccccccccto........o32o...',
      '..o%$##..oJjjjhoyyyoJjjjho.......o32o...',
      '..o%##o..oJjjjho...oJjjjho.......o32o...',
      '...o%#o..oJjjjho...oJjjjho.......o32o...',
      '....o%#o.oJjjjho...oJjjjho.......o32o...',
      '.....o$o.oJjjjho...oJjjjho.......o32o...',
      '......o$oojhhhho...ojhhhho.......o32o...',
      '.......oooJjjjho...oJjjjho.......o32o...',
      '.........oYYYYYo...oYYYYYo.......o32o...',
      '.........oJjjjho...oJjjjho.......o32o...',
      '.........oJjjjho...oJjjjho.......o32o...',
      '.........oJjjjho...oJjjjho.......o32o...',
      '.........oJjjjho...oJjjjho.......o32o...',
      '.........oJjjjho...oJjjjho.......o32o...',
      '.........oJjjjho...oJjjjho.......o32o...',
      '........oeDDDDDio.oeDDDDDio......o32o...',
      '........oeDDDDDio.oeDDDDDio......o32o...',
      '........ooooooooo.ooooooooo......gYYg...'
    ];
    K1('kp_idle1', _kp_idle1);
    K1('kp_walk0', ed(K, {
      19: '.......o%o%$$oYyyyyyYo$$#o.......o32o...',
      20: '.....o%o%$$#jjoyyyyyojj%$$#o.....o32o...',
      21: '....o%o%$#Jjjjjjjjjjjjjjh%$#o....o32o...',
      22: '...o%#ojjjjjjjjjjjjjjjjjhhhhoo...o32o...',
      23: '..o%oKkkSojJJJJJjjjjjjjjjoKkkSo..o32o...',
      24: '.o%$oKkkSojjjjjjjhjjjjjjjoKkkSo..o32o...',
      25: '.o%oKkkSohhhhYhhYhhYhhhhhhoKkkSo.o32o...',
      26: 'o%$oKkkSojjjjYjjYjjYjjjjjhoKkkSo.o32o...',
      27: 'o%$oKkkSojjjjYYYYYYYjjjjjhoKkkSo.o32o...',
      31: 'o%#$$$oKkSohhhhhhhhhhhhhhooKkSo..o32o...',
      32: 'o%$#$$oKkSojjjjjjjjjjjjjhooKkSo..o32o...',
      33: 'o%$$#$$oKkSojjjjjjjjjjjho..oKkSo.o32o...',
      34: 'o%#$$$$oKkSoyyyyyyyyyyyygo.oKkSo.o32o...',
      35: 'o%$#$$$oKkSoyyyo&&&oyyyygo..oKkSoo11o...',
      36: 'o%$$#$#oKkSogggggggggggggo..oKkSoo11o...',
      37: 'o%#$$$#oKkSoccccccccccccto..oKkSoo32o...',
      38: 'o%$#$#ooKkSoccccccccccccto..oKkoKKKKo...',
      39: 'o%$$##ooKkSoccccYccccccto...oKkoKkkKo...',
      40: '.o%#$#o.okkoccccyccccccto....okkoo32o...',
      41: '.o%$##o...oCcccccccccccto........o32o...',
      42: '..o%$##...oYyyyyyyyyyyyYo........o32o...',
      43: '..o%##oJjjjhottt...tttoJjjjho....o32o...',
      44: '...o%#oJjjjho.........oJjjjho....o32o...',
      45: '....o%oJjjjho.........oJjjjho....o32o...',
      46: '.....ooJjjjho.........oJjjjho....o32o...',
      47: '......oJjjjho.........oJjjjho....o32o...',
      48: '......ojhhhho.........ojhhhho....o32o...',
      49: '......oJjjjho.........oJjjjho....o32o...',
      50: '......oYYYYYo.........oYYYYYo....o32o...',
      51: '......oJjjjho.........oJjjjho....o32o...',
      52: '......oJjjjho.........oJjjjho....o32o...',
      53: '......oJjjjho.........oJjjjho....o32o...',
      54: '......oJjjjho.........oJjjjho....o32o...',
      55: '......oJjjjho.........oJjjjho....o32o...',
      56: '......oJjjjho.........oJjjjho....o32o...',
      57: '.....oeDDDDDio.......oeDDDDDio...o32o...',
      58: '.....oeDDDDDio.......oeDDDDDio...o32o...',
      59: '.....ooooooooo.......ooooooooo...gYYg...',
    }));
    const _kp_walk1 = [
      '........................................',
      '...........o..o..o..o..o.......W..W..W..',
      '..........oYooYooYooYooYo......Wb.Wb.Wb.',
      '.........oGYYoYYoYYoYYoYYGo....Wb.Wb.Wb.',
      '.........oGYY#YYY#YYY#YYYGo....Wb.Wb.Wb.',
      '.........ogGGGGGGGGGGGGGGgo....Wb.Wb.Wb.',
      '..........omNNNNNNNNNNNNno.....Wb.Wb.Wb.',
      '.........omNNNNNNNNNNNNNNno....Wb.Wb.Wb.',
      '.........oNnKKKKKKKKKKKKnNo....Wb.Wb.Wb.',
      '.........oNnkKoooKKoooKknNo....Wb.Wb.Wb.',
      '.........oNnKKoWoKKKoWoKnNo....Wb.Wb.Wb.',
      '.........oNnKKqpqKKKqpqKnNo....WWWWWWWW.',
      '.........oNnKKKKkkKKKKKKnNo....obbbbbbo.',
      '.........oNnKKKoSkoKKKKKnNo......gYYg...',
      '.........oNnnnnnnnnnnnnnnNo......oYYo...',
      '.........onNNNNoqqoNNNNno........gyyg...',
      '.........onNNNNNNNNNNNNno........o32o...',
      '..........onNNNNNNNNNNno.........o32o...',
      '............onNNNNNNno...........o32o...',
      '..............okkkko.............o32o...',
      '.......o%o%$$oYyyyyyYo$$#o.......o32o...',
      '.....o%o%$$#jjoyyyyyojj%$$#o.....o32o...',
      '....o%o%$#Jjjjjjjjjjjjjjh%$#o....o32o...',
      '...o%#ojjjjjjjjjjjjjjjjjhhhhoo...o32o...',
      '..o%oKkkSojJJJJJjjjjjjjjjoKkkSo..o32o...',
      '.o%$oKkkSojjjjjjjhjjjjjjjoKkkSo..o32o...',
      '.o%oKkkSohhhhYhhYhhYhhhhhhoKkkSo.o32o...',
      'o%$oKkkSojjjjYjjYjjYjjjjjhoKkkSo.o32o...',
      'o%$oKkkSojjjjYYYYYYYjjjjjhoKkkSo.o32o...',
      'o%#oKkkSoJhhhhhhYhhhhhhhhhoKkkSo.o32o...',
      'o%$#oSSSSojjjjjjYjjjjjjjjhoSSSSo.o32o...',
      'o%$$oYyyyojjjjjyYyjjjjjjhooYyyyo.o32o...',
      'o%#$$oKkSoJhhhhhhhhhhhhhho.oKkSo.o32o...',
      'o%$#$oKkSoJjjjjjjjjjjjjjho.oKkSo.o32o...',
      'o%$$#$oKkSojjjjjjjjjjjjho...oKkSoo32o...',
      'o%#$$$oKkSoyyyyyyyyyyyyygo..oKkSoo11o...',
      'o%$#$$oKkSoyyyyo&&&oyyyygo...oKkSo11o...',
      'o%$$#$oKkSoggggggggggggggo...oKkSo32o...',
      'o%#$$$oKkSocccccccccccccto...oKoKKKKo...',
      'o%$#$#oKkSocccccccccccccto...oKoKkkKo...',
      'o%$$##oKkSocccccYcccoJjjjho..oKkSo32o...',
      '.o%#$#ookkocccccycccoJjjjho...okko32o...',
      '.o%$##o...oCccccccccoJjjjho......o32o...',
      '..o%$##.oJjjjhoyyyyyoJjjjho......o32o...',
      '..o%##o.oJjjjhot...toJjjjho......o32o...',
      '...o%#o.oJjjjho.....ojhhhho......o32o...',
      '....o%#ooJjjjho.....oJjjjho......o32o...',
      '.....o$ooJjjjho.....oYYYYYo......o32o...',
      '......o$ojhhhho.....oJjjjho......o32o...',
      '.......ooJjjjho.....oJjjjho......o32o...',
      '........oYYYYYo.....oJjjjho......o32o...',
      '........oJjjjho.....oJjjjho......o32o...',
      '........oJjjjho.....oJjjjho......o32o...',
      '........oJjjjho.....oJjjjho......o32o...',
      '........oJjjjho....oeDDDDDio.....o32o...',
      '........oJjjjho....oeDDDDDio.....o32o...',
      '........oJjjjho....ooooooooo.....o32o...',
      '.......oeDDDDDio.................o32o...',
      '.......oeDDDDDio.................o32o...',
      '.......ooooooooo.................gYYg...'
    ];
    K1('kp_walk1', _kp_walk1);
    K1('kp_walk2', ed(K, {
      19: '......o%#o%$$oYyyyyyYo$$#o.......o32o...',
      20: '....o%$o%$$#jjoyyyyyojj%$$#o.....o32o...',
      21: '...o%$o%$#Jjjjjjjjjjjjjjh%$#o....o32o...',
      22: '..o%#$ojjjjjjjjjjjjjjjjjhhhho....o32o...',
      23: '.o%$oKkkSojJJJJJjjjjjjjjjoKkkSo..o32o...',
      24: 'o%$$oKkkSojjjjjjjhjjjjjjjoKkkSo..o32o...',
      25: 'o%#oKkkSohhhhYhhYhhYhhhhhhoKkkSo.o32o...',
      26: 'o%$oKkkSojjjjYjjYjjYjjjjjhoKkkSo.o32o...',
      27: 'o%$oKkkSojjjjYYYYYYYjjjjjhoKkkSo.o32o...',
      31: 'o%#oKkSo#oJhhhhhhhhhhhhhho...oKkSo32o...',
      32: 'o%$oKkSo#oJjjjjjjjjjjjjjho...oKkSo32o...',
      33: 'o%$$oKkSooJjjjjjjjjjjjjho.....oKko32o...',
      34: 'o%#$oKkSooYyyyyyyyyyyyyygo....oKko32o...',
      35: 'o%$#oKkSooYyyyyo&&&oyyyygo.....oKo11o...',
      36: 'o%$$oKkSooyggggggggggggggo.....oKo11o...',
      37: 'o%#$oKkSooCcccccccccccccto.....oKo32o...',
      38: 'o%$#oKkSooCcccccccccccccto.....oKKKKo...',
      39: 'o%$$oKkSooCcccccYccccccto......oKkkKo...',
      40: 'o%#$#okkooCcccccyccccccto.......oo32o...',
      41: 'o%$##o....oCcccccccccccto........o32o...',
      42: '.o%$##....oYyyyyyyyyyyyYo........o32o...',
      43: '.o%##o.....ooJjjoJjjjhoo.........o32o...',
      44: '..o%#o......oJjjoJjjjho..........o32o...',
      45: '...o%#o.....oJjjoJjjjho..........o32o...',
      46: '....o$o.....oJjjoJjjjho..........o32o...',
      47: '.....o$o....oJjjoJjjjho..........o32o...',
      48: '......oo....ojhhojhhhho..........o32o...',
      49: '............oJjjoJjjjho..........o32o...',
      50: '............oYYYoYYYYYo..........o32o...',
      51: '............oJjjoJjjjho..........o32o...',
      52: '............oJjjoJjjjho..........o32o...',
      53: '............oJjjoJjjjho..........o32o...',
      54: '............oJjjoJjjjho..........o32o...',
      55: '............oJjjoJjjjho..........o32o...',
      56: '............oJjjoJjjjho..........o32o...',
      57: '...........oeDDoeDDDDDio.........o32o...',
      58: '...........oeDDoeDDDDDio.........o32o...',
      59: '...........ooooooooooooo.........gYYg...',
    }));
    const _kp_walk3 = [
      '........................................',
      '...........o..o..o..o..o.......W..W..W..',
      '..........oYooYooYooYooYo......Wb.Wb.Wb.',
      '.........oGYYoYYoYYoYYoYYGo....Wb.Wb.Wb.',
      '.........oGYY#YYY#YYY#YYYGo....Wb.Wb.Wb.',
      '.........ogGGGGGGGGGGGGGGgo....Wb.Wb.Wb.',
      '..........omNNNNNNNNNNNNno.....Wb.Wb.Wb.',
      '.........omNNNNNNNNNNNNNNno....Wb.Wb.Wb.',
      '.........oNnKKKKKKKKKKKKnNo....Wb.Wb.Wb.',
      '.........oNnkKoooKKoooKknNo....Wb.Wb.Wb.',
      '.........oNnKKoWoKKKoWoKnNo....Wb.Wb.Wb.',
      '.........oNnKKqpqKKKqpqKnNo....WWWWWWWW.',
      '.........oNnKKKKkkKKKKKKnNo....obbbbbbo.',
      '.........oNnKKKoSkoKKKKKnNo......gYYg...',
      '.........oNnnnnnnnnnnnnnnNo......oYYo...',
      '.........onNNNNoqqoNNNNno........gyyg...',
      '.........onNNNNNNNNNNNNno........o32o...',
      '..........onNNNNNNNNNNno.........o32o...',
      '............onNNNNNNno...........o32o...',
      '..............okkkko.............o32o...',
      '.......o%o%$$oYyyyyyYo$$#o.......o32o...',
      '.....o%o%$$#jjoyyyyyojj%$$#o.....o32o...',
      '....o%o%$#Jjjjjjjjjjjjjjh%$#o....o32o...',
      '...o%#ojjjjjjjjjjjjjjjjjhhhhoo...o32o...',
      '..o%oKkkSojJJJJJjjjjjjjjjoKkkSo..o32o...',
      '.o%$oKkkSojjjjjjjhjjjjjjjoKkkSo..o32o...',
      '.o%oKkkSohhhhYhhYhhYhhhhhhoKkkSo.o32o...',
      'o%$oKkkSojjjjYjjYjjYjjjjjhoKkkSo.o32o...',
      'o%$oKkkSojjjjYYYYYYYjjjjjhoKkkSo.o32o...',
      'o%#oKkkSoJhhhhhhYhhhhhhhhhoKkkSo.o32o...',
      'o%$#oSSSSojjjjjjYjjjjjjjjhoSSSSo.o32o...',
      'o%$$oYyyyojjjjjyYyjjjjjjhooYyyyo.o32o...',
      'o%#$oKkSooJhhhhhhhhhhhhhho..oKkSoo32o...',
      'o%$#oKkSooJjjjjjjjjjjjjjho..oKkSoo32o...',
      'o%$$#oKkSoJjjjjjjjjjjjjho....oKkSo32o...',
      'o%#$$oKkSoYyyyyyyyyyyyyygo...oKkSo11o...',
      'o%$#$oKkSoYyyyyo&&&oyyyygo....oKko11o...',
      'o%$$#oKkSoyggggggggggggggo....oKko32o...',
      'o%#$$oKkSoCcccccccccccccto....ooKKKKo...',
      'o%$#$oKkSoCcccccccccccccto....ooKkkKo...',
      'o%$$#oKkSooJjjjhoccccccto.....oKko32o...',
      '.o%#$#okkooJjjjhoccccccto......oko32o...',
      '.o%$##o...oJjjjhoccccccto........o32o...',
      '..o%$##...oJjjjhoyoJjjjho........o32o...',
      '..o%##o...oJjjjho.oJjjjho........o32o...',
      '...o%#o...ojhhhho.oJjjjho........o32o...',
      '....o%#o..oJjjjho.oJjjjho........o32o...',
      '.....o$o..oYYYYYo.oJjjjho........o32o...',
      '......o$o.oJjjjho.ojhhhho........o32o...',
      '.......oo.oJjjjho.oJjjjho........o32o...',
      '..........oJjjjho.oYYYYYo........o32o...',
      '..........oJjjjho.oJjjjho........o32o...',
      '..........oJjjjho.oJjjjho........o32o...',
      '..........oJjjjho.oJjjjho........o32o...',
      '.........oeDDDDDiooJjjjho........o32o...',
      '.........oeDDDDDiooJjjjho........o32o...',
      '.........ooooooooooJjjjho........o32o...',
      '.................oeDDDDDio.......o32o...',
      '.................oeDDDDDio.......o32o...',
      '.................ooooooooo.......gYYg...'
    ];
    K1('kp_walk3', _kp_walk3);
    const _kp_thrust0 = [
      '.................................o32o...',
      '...........o..o..o..o..o.........o32o...',
      '..........oYooYooYooYooYo........o32o...',
      '.........oGYYoYYoYYoYYoYYGo......o32o...',
      '.........oGYY#YYY#YYY#YYYGo......o32o...',
      '.........ogGGGGGGGGGGGGGGgo......o32o...',
      '..........omNNNNNNNNNNNNno.......o32o...',
      '.........omNNNNNNNNNNNNNNno......o32o...',
      '.........oNnKKKKKKKKKKKKnNo......o32o...',
      '.........oNnkKqqqKKqqqKknNo......o32o...',
      '.........oNnKKoWoKKKoWoKnNo......o32o...',
      '.........oNnKKqpqKKKqpqKnNo......o32o...',
      '.........oNnKKKKkkKKKKKKnNo......o32o...',
      '.........oNnKKKoSkoKKKKKnNo......o32o...',
      '.........oNnnnnnnnnnnnnnnNo......o32o...',
      '.........onNNNNoqqoNNNNno........o32o...',
      '..........onNNNNNNNNNNNNno.......o32o...',
      '...........onNNNNNNNNNNno.....ooKKKKo...',
      '.............onNNNNNNno.......ooKkkKo...',
      '..............okkkko......oKkkSo.o11o...',
      '.....o%#$o%$$oYyyyyyYo$$#o.oKkkSoo32o...',
      '...o%$#o%$$#jjoyyyyyojj%$$#ooKkkSo32o...',
      '..o%$$o%$#Jjjjjjjjjjjjjjh%$#ooKkko32o...',
      '.o%#$$ojjjjjjjjjjjjjjjjjhhhho.oKko32o...',
      'o%$oKkkSojjJJJJJjjjjjjjjjjho.....o32o...',
      'o%$oKkkSojjjjjjjjhjjjjjjjjho.....o32o...',
      'o%#oKkkSohhhhYhhYhhYhhhhhhho.....o32o...',
      'o%$oKkkSojjjjYjjYjjYjjjjjho......o32o...',
      'o%$oKkkSojjjjYYYYYYYjjjjjho......o32o...',
      'o%#oKkkSoJhhhhhhYhhhhhhhhho......o32o...',
      'o%$oKkkSoJjjjjjjYjjjjjjjjho......o32o...',
      'o%$oKkkSoJjjjjjyYyjjjjjjho.......o32o...',
      'o%#$oKkSooJhhhhhhhhhhhhhho.......o32o...',
      'o%$#oKkSooJjjjjjjjjjjjjjho.......o32o...',
      'o%$$#$$#ooJjjjjjjjjjjjjho........o32o...',
      'o%#$$$$#ooYyyyyyyyyyyyyygo.......o32o...',
      'o%$#$$$#ooYyyyyo&&&oyyyygo.......o32o...',
      'o%$$#$#o.oyggggggggggggggo.......o32o...',
      'o%#$$$#o.oCcccccccccccccto.......o32o...',
      'o%$#$#o..oCcccccccccccccto.......o32o...',
      'o%$$##o..oCcccccYccccccto........o32o...',
      'o%#$#o...oCcccccyccccccto........o32o...',
      'o%$##o....oCcccccccccccto........o32o...',
      'o%$##oJjjjhoyyyyyyyyyyyoJjjjho...o32o...',
      'o%##ooJjjjhotttt...ttttoJjjjho...o32o...',
      '.o%#ooJjjjho...........oJjjjho...o32o...',
      '..o%#oJjjjho...........oJjjjho...o32o...',
      '...o$oJjjjho...........oJjjjho...o32o...',
      '....oojhhhho...........ojhhhho...o32o...',
      '.....oJjjjho...........oJjjjho...o32o...',
      '.....oYYYYYo...........oYYYYYo...o32o...',
      '.....oJjjjho...........oJjjjho...o32o...',
      '.....oJjjjho...........oJjjjho...o32o...',
      '.....oJjjjho...........oJjjjho...o32o...',
      '.....oJjjjho...........oJjjjho...o32o...',
      '.....oJjjjho...........oJjjjho...o32o...',
      '.....oJjjjho...........oJjjjho...o32o...',
      '....oeDDDDDio.........oeDDDDDio..o32o...',
      '....oeDDDDDio.........oeDDDDDio..o32o...',
      '....ooooooooo.........ooooooooo..gYYg...'
    ];
    K1('kp_thrust0', _kp_thrust0);
    const _kp_thrust1 = [
      '........................................',
      '........................................',
      '...........o..o..o..o..o................',
      '..........oYooYooYooYooYo...............',
      '.........oGYYoYYoYYoYYoYYGo.............',
      '.........oGYY#YYY#YYY#YYYGo.............',
      '.........ogGGGGGGGGGGGGGGgo.............',
      '..........omNNNNNNNNNNNNno..............',
      '.........omNNNNNNNNNNNNNNno.............',
      '.........oNnKKKKKKKKKKKKnNo.............',
      '.........oNnkKqqqKKqqqKknNo....W..W..W..',
      '.........oNnKKoWoKKKoWoKnNo....Wb.Wb.Wb.',
      '.........oNnKKqpqKKKqpqKnNo....Wb.Wb.Wb.',
      '.........oNnKKKKkkKKKKKKnNo....Wb.Wb.Wb.',
      '.........oNnKKKoSkoKKKKKnNo....Wb.Wb.Wb.',
      '.........oNnnnnnnnnnnnnnnNo....Wb.Wb.Wb.',
      '.........onNNNNoqqoNNNNno......Wb.Wb.Wb.',
      '..........onNNNNNNNNNNNNno.....Wb.Wb.Wb.',
      '...........onNNNNNNNNNNno......Wb.Wb.Wb.',
      '.............onNNNNNNno........Wb.Wb.Wb.',
      '..............okkkko...........WWWWWWWW.',
      '.......o%o%$$oYyyyyyYo$$#o.....obbbbbbo.',
      '.....o%o%$$#jjoyyyyyojj%$$#o.....gYYg...',
      '....o%o%$#Jjjjjjjjjjjjjjh%$#o....oYYo...',
      '...oKkkSojjjjjjjjjjjjjjjhoKkkSo..gyyg...',
      '..ooKkkSojjJJJJJjjjjjjjjjjoKkkSo.o32o...',
      '.o%oKkkSojjjjjjjjhjjjjjjjjhoKkkSoo32o...',
      '.o%oKkkSohhhhYhhYhhYhhhhhhhooKkkSo32o...',
      'o%$oKkkSojjjjYjjYjjYjjjjjho..oKkko32o...',
      'o%$oKkkSojjjjYYYYYYYjjjjjho...oKko32o...',
      'o%#oKkkSoJhhhhhhYhhhhhhhhho...oKko32o...',
      'o%$oKkkSoJjjjjjjYjjjjjjjjho...oKko32o...',
      'o%$$oKkSoJjjjjjyYyjjjjjjho....oKko32o...',
      'o%#$oKkSooJhhhhhhhhhhhhhho....oKko32o...',
      'o%$#$$$$#oJjjjjjjjjjjjjjho....ooKKKKo...',
      'o%$$#$$#ooJjjjjjjjjjjjjho.....ooKkkKo...',
      'o%#$$$$#ooYyyyyyyyyyyyyygo.......o32o...',
      'o%$#$$$#ooYyyyyo&&&oyyyygo.......o32o...',
      'o%$$#$#o.oyggggggggggggggo.......o32o...',
      'o%#$$$#o.oCcccccccccccccto.......o32o...',
      'o%$#$#o..oCcccccccccccccto.......o32o...',
      'o%$$##o..oCcccccYccccccto........o32o...',
      '.o%#$#o..oCcccccyccccccto........o32o...',
      '.o%$#oJjjjhocccccccccccoJjjjho...o32o...',
      '..o%$oJjjjhoyyyyyyyyyyyoJjjjho...o11o...',
      '..o%#oJjjjhotttt...ttttoJjjjho...o11o...',
      '...o%oJjjjho...........oJjjjho...o32o...',
      '....ooJjjjho...........oJjjjho...o32o...',
      '.....ojhhhho...........ojhhhho...o32o...',
      '.....oJjjjho...........oJjjjho...o32o...',
      '.....oYYYYYo...........oYYYYYo...o32o...',
      '.....oJjjjho...........oJjjjho...o32o...',
      '.....oJjjjho...........oJjjjho...o32o...',
      '.....oJjjjho...........oJjjjho...o32o...',
      '.....oJjjjho...........oJjjjho...o32o...',
      '.....oJjjjho...........oJjjjho...o32o...',
      '.....oJjjjho...........oJjjjho...o32o...',
      '....oeDDDDDio.........oeDDDDDio..o32o...',
      '....oeDDDDDio.........oeDDDDDio..o32o...',
      '....ooooooooo.........ooooooooo..gYYg...'
    ];
    K1('kp_thrust1', _kp_thrust1);
    P.anim('kp_idle', ['kp_idle0', 'kp_idle1'], 2);
    P.anim('kp_walk', ['kp_walk0', 'kp_walk1', 'kp_walk2', 'kp_walk3'], 7);
    P.anim('kp_thrust', ['kp_thrust0', 'kp_thrust1'], 10);
  }

  /* ---- THE QUEEN ---- */
  function queenSprite() {
    const Q = [
      '........................................',
      '.............oxRRRRRro..................',
      '...........oxRRRRRRRRRro................',
      '..........oxRRoRRoRRRRoro...............',
      '.........oxRoYWYoRRoYWYoro..............',
      '........oxoyYYYWYYYWYYYyoo..............',
      '.........oogGGGGGGGGGGGGgoo.............',
      '........ooRxKKKKKKKKKKKxrRoxxo..........',
      '........ooRrkoqqqoKoqqKorRoxxo..........',
      '........ooRrKKoWoKKKoWoKrRoxxo..........',
      '........ooRrKKqpqKKKqpqKrRoxxo..........',
      '........ooRrKKKKkkKKKKKKrRoxxo..........',
      '........ooRxKKKoSkoKKKKxrRoxxo..........',
      '........ooRrKKKoqqoKKKKKrRoxxo..........',
      '........ooRrKKKKKKKKKKKKrRoxxxo.........',
      '........oRRoKKKKKKKKKKKKo.xxxxo.........',
      '........oRRRRokkkkkko.....xxxxo.........',
      '.......oRRRR..okkkko......xxxxo.........',
      '.......oRRRR..okkkko......xxxxo.........',
      '.......oRRRRo877777775o...xxxxo.........',
      '.......oRRo8777777777775o.xxxxo.........',
      '.......oRo8777oWWWWWo7775oxxxxo.........',
      '.......oRo877777777777775oxxxxo.........',
      '....o8775o877777777777775o8775o.........',
      '....o8775o87777777777775oo8775o.........',
      '...o8775oo87777777777775o.o8775o........',
      '...o8775o.o8777YyyyY7775o.o8775o........',
      '...o8775o.o8777777777775o.o8775o........',
      '...o8775o.o877777777775o..o8775o........',
      '....oSSS5oo8777YyyyY775o..oSSS5o........',
      '....oYyyyo.o87777777775o..oYyyyo........',
      '....oKkSo..o87777777775o...oKkSo........',
      '....oKkSo.o877777777775o...oKkSo........',
      '.....oKkSoo8777777777775o...oKkSo.......',
      '.....oKkSooYyyyyyyyyyyygo...oKkSo.......',
      '.....oKkSooYyyyyoXoyyyygo....oKkSo......',
      '.....oKkSooyggggggggggggo....oKkSo......',
      '.....oKkSooYyyyyyyyyyyyg.....oKkSo......',
      '.....oKkSooYyyyyyyyyyyygo....oKkSo......',
      '.....oKkSo87777777777775o....oKkSo......',
      '......okko877777777777775o....okko......',
      '........o8775777777775775o..............',
      '........o87757777777757775o.............',
      '.......o877757777777757775o.............',
      '.......o8777577777777577775o............',
      '.......o8777577777777577775o............',
      '......o87777577777777577775o............',
      '......o87777577777777577775o............',
      '......o877775777777775777775o...........',
      '......o877775777777775777775o...........',
      '.....o8777775777777775777775o...........',
      '.....o8777775777777775777775o...........',
      '.....o87777757777777757777775o..........',
      '.....o87777757777777757777775o..........',
      '....o877777757777777757777775o..........',
      '....o877777757777777757777775o..........',
      '....o877777757777777757777775o..........',
      '....o8777777577777777577777775o.........',
      '....oYyyyyyyyyyyyyyyyyyyyyyyyygo........',
      '....oooooooooooooooooooooooooooo........'
    ];
    K1('qn_idle0', Q);
    const _qn_idle1 = [
      '........................................',
      '........................................',
      '.............oxRRRRRro..................',
      '...........oxRRRRRRRRRro................',
      '..........oxRRoRRoRRRRoro...............',
      '.........oxRoYWYoRRoYWYoro..............',
      '........oxoyYYYWYYYWYYYyoo..............',
      '.........oogGGGGGGGGGGGGgoo.............',
      '........ooRxKKKKKKKKKKKxrRoxxo..........',
      '........ooRrkKqqqKKqqqKkrRoxxo..........',
      '........ooRrKKqqqKKqqqKKrRoxxo..........',
      '........ooRrKKKKKKKKKKKKrRoxxo..........',
      '........ooRrKKKKkkKKKKKKrRoxxo..........',
      '........ooRxKKKoSkoKKKKxrRoxxo..........',
      '........ooRrKKKoqqoKKKKKrRoxxo..........',
      '........ooRrKKKKKKKKKKKKrRoxxxo.........',
      '........oRRoKKKKKKKKKKKKo.xxxxo.........',
      '........oRRRRokkkkkko.....xxxxo.........',
      '.......oRRRR..okkkko......xxxxo.........',
      '.......oRRRR..okkkko......xxxxo.........',
      '.......oRRRRo877777775o...xxxxo.........',
      '.......oRRo8777777777775o.xxxxo.........',
      '.......oRo8777oWWWWWo7775oxxxxo.........',
      '.......oRo877777777777775oxxxxo.........',
      '....o8775o877777777777775o8775o.........',
      '....o8775o87777777777775oo8775o.........',
      '...o8775oo87777777777775o.o8775o........',
      '...o8775o.o8777YyyyY7775o.o8775o........',
      '...o8775o.o8777777777775o.o8775o........',
      '...o8775o.o877777777775o..o8775o........',
      '....oSSS5oo8777YyyyY775o..oSSS5o........',
      '....oYyyyo.o87777777775o..oYyyyo........',
      '....oKkSo..o87777777775o...oKkSo........',
      '....oKkSo.o877777777775o...oKkSo........',
      '.....oKkSoo8777777777775o...oKkSo.......',
      '.....oKkSooYyyyyyyyyyyygo...oKkSo.......',
      '.....oKkSooYyyyyoXoyyyygo....oKkSo......',
      '.....oKkSooyggggggggggggo....oKkSo......',
      '.....oKkSooYyyyyyyyyyyyg.....oKkSo......',
      '.....oKkSooYyyyyyyyyyyygo....oKkSo......',
      '.....oKkSo87777777777775o....oKkSo......',
      '......okko877777777777775o....okko......',
      '........o8775777777775775o..............',
      '........o87757777777757775o.............',
      '.......o877757777777757775o.............',
      '.......o8777577777777577775o............',
      '.......o8777577777777577775o............',
      '......o87777577777777577775o............',
      '......o87777577777777577775o............',
      '.....o8777775777777775777775o...........',
      '.....o8777775777777775777775o...........',
      '.....o87777757777777757777775o..........',
      '.....o87777757777777757777775o..........',
      '....o877777757777777757777775o..........',
      '....o877777757777777757777775o..........',
      '....o8777777577777777577777775o.........',
      '....o8777777577777777577777775o.........',
      '....o8777777577777777577777775o.........',
      '...o87777777577777777577777775o.........',
      '...ooooooooooooooooooooooooooooo........'
    ];
    K1('qn_idle1', _qn_idle1);
    K1('qn_walk0', ed(Q, {
      31: '......oKkSoo87777777775o..oKkSo.........',
      32: '......oKkSo877777777775o..oKkSo.........',
      33: '.......oKkSo777777777775o..oKkSo........',
      34: '.......oKkSoyyyyyyyyyyygo..oKkSo........',
      35: '.......oKkSoyyyyoXoyyyygo...oKkSo.......',
      36: '.......oKkSoggggggggggggo...oKkSo.......',
      37: '.......oKkSoyyyyyyyyyyyg....oKkSo.......',
      38: '.......oKkSoyyyyyyyyyyygo...oKkSo.......',
      39: '.......oKkSo777777777775o...oKkSo.......',
      40: '........okko7777777777775o...okko.......',
      58: '...oYyyyyyyyyyyyyyyyyyyyyyyyyyygo.......',
      59: '...oooooooooooooooooooooooooooooo.......',
    }));
    const _qn_walk1 = [
      '........................................',
      '........................................',
      '.............oxRRRRRro..................',
      '...........oxRRRRRRRRRro................',
      '..........oxRRoRRoRRRRoro...............',
      '.........oxRoYWYoRRoYWYoro..............',
      '........oxoyYYYWYYYWYYYyoo..............',
      '.........oogGGGGGGGGGGGGgoo.............',
      '........ooRxKKKKKKKKKKKxrRoxxo..........',
      '........ooRrkoqqqoKoqqKorRoxxo..........',
      '........ooRrKKoWoKKKoWoKrRoxxo..........',
      '........ooRrKKqpqKKKqpqKrRoxxo..........',
      '........ooRrKKKKkkKKKKKKrRoxxo..........',
      '........ooRxKKKoSkoKKKKxrRoxxo..........',
      '........ooRrKKKoqqoKKKKKrRoxxo..........',
      '........ooRrKKKKKKKKKKKKrRoxxxo.........',
      '........oRRoKKKKKKKKKKKKo.xxxxo.........',
      '........oRRRRokkkkkko.....xxxxo.........',
      '.......oRRRR..okkkko......xxxxo.........',
      '.......oRRRR..okkkko......xxxxo.........',
      '.......oRRRRo877777775o...xxxxo.........',
      '.......oRRo8777777777775o.xxxxo.........',
      '.......oRo8777oWWWWWo7775oxxxxo.........',
      '.......oRo877777777777775oxxxxo.........',
      '....o8775o877777777777775o8775o.........',
      '....o8775o87777777777775oo8775o.........',
      '...o8775oo87777777777775o.o8775o........',
      '...o8775o.o8777YyyyY7775o.o8775o........',
      '...o8775o.o8777777777775o.o8775o........',
      '...o8775o.o877777777775o..o8775o........',
      '....oSSS5oo8777YyyyY775o..oSSS5o........',
      '....oYyyyo.o87777777775o..oYyyyo........',
      '.....oKkSo.o87777777775o...oKkSo........',
      '.....oKkSoo877777777775o...oKkSo........',
      '......oKkSo8777777777775o...oKkSo.......',
      '......oKkSoYyyyyyyyyyyygo...oKkSo.......',
      '......oKkSoYyyyyoXoyyyygo....oKkSo......',
      '......oKkSoyggggggggggggo....oKkSo......',
      '......oKkSoYyyyyyyyyyyyg.....oKkSo......',
      '......oKkSoYyyyyyyyyyyygo....oKkSo......',
      '......oKkSo7777777777775o....oKkSo......',
      '.......okko77777777777775o....okko......',
      '........o8775777777775775o..............',
      '........o87757777777757775o.............',
      '.......o877757777777757775o.............',
      '.......o8777577777777577775o............',
      '.......o8777577777777577775o............',
      '......o87777577777777577775o............',
      '......o87777577777777577775o............',
      '.....o8777775777777775777775o...........',
      '.....o8777775777777775777775o...........',
      '.....o87777757777777757777775o..........',
      '.....o87777757777777757777775o..........',
      '....o877777757777777757777775o..........',
      '....o877777757777777757777775o..........',
      '....o8777777577777777577777775o.........',
      '....o8777777577777777577777775o.........',
      '....o8777777577777777577777775o.........',
      '...o87777777577777777577777775o.........',
      '...ooooooooooooooooooooooooooooo........'
    ];
    K1('qn_walk1', _qn_walk1);
    K1('qn_walk2', ed(Q, {
      31: '...oKkSo...o87777777775o.....oKkSo......',
      32: '...oKkSo..o877777777775o.....oKkSo......',
      33: '....oKkSo.o8777777777775o.....oKkSo.....',
      34: '....oKkSo.oYyyyyyyyyyyygo.....oKkSo.....',
      35: '....oKkSo.oYyyyyoXoyyyygo......oKkSo....',
      36: '....oKkSo.oyggggggggggggo......oKkSo....',
      37: '....oKkSo.oYyyyyyyyyyyyg.......oKkSo....',
      38: '....oKkSo.oYyyyyyyyyyyygo......oKkSo....',
      39: '....oKkSoo87777777777775o......oKkSo....',
      40: '.....okkoo877777777777775o......okko....',
      58: '...oYyyyyyyyyyyyyyyyyyyyyyyyyyygo.......',
      59: '...oooooooooooooooooooooooooooooo.......',
    }));
    const _qn_walk3 = [
      '........................................',
      '........................................',
      '.............oxRRRRRro..................',
      '...........oxRRRRRRRRRro................',
      '..........oxRRoRRoRRRRoro...............',
      '.........oxRoYWYoRRoYWYoro..............',
      '........oxoyYYYWYYYWYYYyoo..............',
      '.........oogGGGGGGGGGGGGgoo.............',
      '........ooRxKKKKKKKKKKKxrRoxxo..........',
      '........ooRrkoqqqoKoqqKorRoxxo..........',
      '........ooRrKKoWoKKKoWoKrRoxxo..........',
      '........ooRrKKqpqKKKqpqKrRoxxo..........',
      '........ooRrKKKKkkKKKKKKrRoxxo..........',
      '........ooRxKKKoSkoKKKKxrRoxxo..........',
      '........ooRrKKKoqqoKKKKKrRoxxo..........',
      '........ooRrKKKKKKKKKKKKrRoxxxo.........',
      '........oRRoKKKKKKKKKKKKo.xxxxo.........',
      '........oRRRRokkkkkko.....xxxxo.........',
      '.......oRRRR..okkkko......xxxxo.........',
      '.......oRRRR..okkkko......xxxxo.........',
      '.......oRRRRo877777775o...xxxxo.........',
      '.......oRRo8777777777775o.xxxxo.........',
      '.......oRo8777oWWWWWo7775oxxxxo.........',
      '.......oRo877777777777775oxxxxo.........',
      '....o8775o877777777777775o8775o.........',
      '....o8775o87777777777775oo8775o.........',
      '...o8775oo87777777777775o.o8775o........',
      '...o8775o.o8777YyyyY7775o.o8775o........',
      '...o8775o.o8777777777775o.o8775o........',
      '...o8775o.o877777777775o..o8775o........',
      '....oSSS5oo8777YyyyY775o..oSSS5o........',
      '....oYyyyo.o87777777775o..oYyyyo........',
      '....oKkSo..o87777777775o....oKkSo.......',
      '....oKkSo.o877777777775o....oKkSo.......',
      '.....oKkSoo8777777777775o....oKkSo......',
      '.....oKkSooYyyyyyyyyyyygo....oKkSo......',
      '.....oKkSooYyyyyoXoyyyygo.....oKkSo.....',
      '.....oKkSooyggggggggggggo.....oKkSo.....',
      '.....oKkSooYyyyyyyyyyyyg......oKkSo.....',
      '.....oKkSooYyyyyyyyyyyygo.....oKkSo.....',
      '.....oKkSo87777777777775o.....oKkSo.....',
      '......okko877777777777775o.....okko.....',
      '........o8775777777775775o..............',
      '........o87757777777757775o.............',
      '.......o877757777777757775o.............',
      '.......o8777577777777577775o............',
      '.......o8777577777777577775o............',
      '......o87777577777777577775o............',
      '......o87777577777777577775o............',
      '.....o8777775777777775777775o...........',
      '.....o8777775777777775777775o...........',
      '.....o87777757777777757777775o..........',
      '.....o87777757777777757777775o..........',
      '....o877777757777777757777775o..........',
      '....o877777757777777757777775o..........',
      '....o8777777577777777577777775o.........',
      '....o8777777577777777577777775o.........',
      '....o8777777577777777577777775o.........',
      '...o87777777577777777577777775o.........',
      '...ooooooooooooooooooooooooooooo........'
    ];
    K1('qn_walk3', _qn_walk3);
    P.anim('qn_idle', ['qn_idle0', 'qn_idle1'], 2);
    P.anim('qn_walk', ['qn_walk0', 'qn_walk1', 'qn_walk2', 'qn_walk3'], 7);
  }

  /* ---- THE DEEP, WHO COOKS ---- */
  function theDeep() {
    const D = [
      '............oWwwwwwwwbo.................',
      '..........oWWWWWwwwwwwwbo...............',
      '........oWwwwwwwwwwwbbbbwbo.............',
      '.......oWwwWWWWWwwwwwwwwwwbo............',
      '......oWwwwwwwwwwwwwbbbbwwwbo...........',
      '......oWwwwWWWWWwwwwwwwwwwwbo...........',
      '.......oWwwwwwwwwwwwbbbbwwbo............',
      '........oWwwwwwwwwwwwwwwwbo.............',
      '.........owbbbbbbbbbbbbbbo..............',
      '.........owooooooooooooobo..............',
      '..........oAaaaaaaaaaaazo...............',
      '.........AAAAAaaaaaaaaaazo..............',
      '........oAaaaaaaaaaaaaaaazo.............',
      '.......oAoWwwboaaaaaoWwwboo.............',
      '.......ooWwwWYYgaaaoWYYgwboo............',
      '......oAoWwwgoogaaaogoogwboo............',
      '......oAoWwwgoogaaaogoogwboo............',
      '......oAaaaaaaaaaaaaaaaaaaazo...........',
      '......oAaaaaaaaaaaaaaaaaaazoo...........',
      '.......oAaaaaaaaaaaaaaaaaazo............',
      '.......oAaaaozzzzzzzzzoaazo.............',
      '........oAaaazzzzAzzzzaazo..............',
      '...oAazooAaaaaaaaaaaaaaazo......oAazo...',
      '...oAazooAaaaaaaaaaaaaaazo......oAazo...',
      '...oAazo.oooWwwwwwwwwwbooo......oAao3o..',
      '....oAazooAoWwwwwwwwwwbozo.....oAazo3o..',
      '....oAazoooWwwwwwwwwwwboo......oAazo3o..',
      '....oAazoooWwwwwwwwwwwboo......oAazo3o..',
      '.....oAazooWwwwwbwbwwwwbo.....oAazoo3o..',
      '.....oAazooWwwwwwwwwwwwbo.....oAazoo3o..',
      '..oAaaaaaoWwwwwwwwwwwwwboaaaaaazo..o3o..',
      '..oAaaaoAoWwwwwwwwwwwwwboaaaaaazo..o3o..',
      '..oAaaaoAoWwwwwwwwwwwwwboaaaaaazo..o3o..',
      '...oAaaoAaobbbbbbbbbbbbboaaaaazo...o3o..',
      '...oAaaoAaaoAaaaaoAaaaoAaaaaaazo.o333o..',
      '...oAaaoAaaaoAaaaoAaaaoAaaaaaazo.oYYYo..',
      '..oAaaaoAaaaoAaaaoAaaaaoAaaaaaazooyyyo..',
      '..oAaaaoAaaaoAaaaoAaaaaoAaaaaaazo.ooo...',
      '...oAaaaoAaaoAaaaoAaaaaoAaaaaazo........',
      '...oAaaoAaaaoAaaaaoAaaaaoAaaaaazo.......',
      '..oAaaaoAaaaoAaaaaoAaaaaoAaaaaazo.......',
      '..oAaaaoAaaaoAaaaaoAaaaaoAaaaaazo.......',
      '..oAaaaoAaaaoAaaaaoAaaaaoAaaaaazo.......',
      '..oAaaaoAaaaoAaaaaaoAaaaaoAaaaazo.......',
      '..oAaaaoAaaaoAaaaaaoAaaaaoAaaaazo.......',
      '..oAaaaoAaaaoAaaaaaoAaaaaaoAaaaazo......',
      '..oAaaaoAaaaoAaaaaaoAaaaaaoAaaaazo......',
      '.oAaaaaoAaaaoAaaaaazoAaaaaoAaaaazo......',
      '..oAaaaoAaaaaoAaaaazoAaaaazoAaaazo......',
      '.oAaaazoAaaaaoAaaaazoAaaaazoAaaazo......',
      '.oAaaazoAaaaaoAaaaaAoAaaaazooAaaazo.....',
      '.oAaaazoAaaaaoAaaaazoAaaaazooAaaazo.....',
      'oAaaaAooAaaazoAaaaazooAaaazo.oAaaazo....',
      'oAaazo.oAaaaAooAaaazooAaaazo..oAaazo....',
      'oAaazooAaaazo.oAaaaAo.oAaaazo..oAaazo...',
      'oAaazooAaaazooAaaazo..oAaaazo...oAaazo..',
      '.....oAaazo..oAaaazo....oAaazo..........',
      '.....oAaaAo..oAaazo.....oAaazo..........',
      '....oAaazo...oAaaAo......oAaazo.........',
      '............oAaazo......................'
    ];
    K1('dp_idle0', D);
    K1('dp_idle1', ed(D, {
      0: '...........oWwwwwwwwwbo.................',
      1: '.........oWWWWWWwwwwwwwbo...............',
      2: '.......oWwwwwwwwwwwwbbbbwbo.............',
      3: '......oWwwwWWWWWwwwwwwwwwwbo............',
      4: '.....oWwwwwwwwwwwwwwbbbbwwwbo...........',
      5: '.....oWwwwwWWWWWwwwwwwwwwwwbo...........',
      6: '......oWwwwwwwwwwwwwbbbbwwbo............',
      7: '.......oWwwwwwwwwwwwwwwwwbo.............',
      23: '...oAazooAaaaaaaaaaaaaaazo......oAao3o..',
      33: '...oAaaoAaobbbbbbbbbbbbboaaaaazo.o333o..',
      34: '...oAaaoAaaoAaaaaoAaaaaoAaaaaaazooYYYo..',
      35: '..oAaaaoAaaoAaaaaoAaaaaoAaaaaaazooyyyo..',
      36: '..oAaaaoAaaoAaaaaoAaaaaoAaaaaaazo.ooo...',
      37: '..oAaaaoAaaoAaaaaoAaaaaoAaaaaaazo.......',
      38: '..oAaaaoAaaoAaaaaaoAaaaaoAaaaaazo.......',
      39: '..oAaaaoAaaaoAaaaaoAaaaaoAaaaaazo.......',
      40: '.oAaaaaoAaaoAaaaaaoAaaaaaoAaaaaazo......',
      41: '.oAaaaoAaaaoAaaaaaaoAaaaaoAaaaaazo......',
      42: '.oAaaaoAaaaoAaaaaaaoAaaaaaoAaaaaazo.....',
      43: '.oAaaaoAaaaoAaaaaaazoAaaaaaoAaaaazo.....',
      44: 'oAaaaaoAaaaoAaaaaazooAaaaaaoAaaaazo.....',
      45: 'oAaaaaoAaaaoAaaaaazooAaaaaaoAaaaazo.....',
      46: 'oAaaaoAaaaaoAaaaaaAo.oAaaaaaoAaaaazo....',
      47: 'oAaaaaoAaaaoAaaaaazo.oAaaaazoAaaaazo....',
      48: 'oAaaaoAaaaaoAaaaazo...oAaaaazoAaaazo....',
      49: 'oAaaaoAaaaaoAaaaazo...oAaaaazooAaaazo...',
      50: 'oAaaoAaaaazoAaaaaAo....oAaaaazoAaaazo...',
      51: 'oAaaoAaaaazoAaaaazo....oAaaaazooAaaazo..',
      52: 'oAaaoAaaazooAaaaazo.....oAaaazo.oAaaazo.',
      53: 'oAaaoAaaaAooAaaazo......oAaaazo...oAaazo',
      54: 'oAaoAaaazo.oAaaaAo.......oAaaazo..oAaazo',
      55: 'oAoAaaazo.oAaaazo.........oAaaazo.oAaazo',
      56: '..oAaazo..oAaaazo..........oAaazo.......',
      57: '.oAaaAo..oAaazo.............oAaazo......',
      58: 'oAaazo...oAaaAo..............oAaazo.....',
      59: '........oAaazo..........................',
    }));
    K1('dp_talk0', ed(D, {
      13: '.......oAaaaaaaaaaaaaaaaazo.............',
      14: '.......ooAaaaazoaaaoAaaaazoo............',
      15: '......oAooooooooaaaooooooooo............',
      16: '......oAoAaaaazoaaaoAaaaazoo............',
      35: '..oAaaaoAaaoAaaaaoAaaaaoAaaaaaazooYYYo..',
      36: '..oAaaaoAaaoAaaaaoAaaaaoAaaaaaazooyyyo..',
      37: '..oAaaaoAaaoAaaaaoAaaaaoAaaaaaazo.ooo...',
      38: '..oAaaaoAaaoAaaaaaoAaaaaoAaaaaazo.......',
      39: '..oAaaaoAaaaoAaaaaoAaaaaoAaaaaazo.......',
      41: '..oAaaaoAaaaoAaaaaoAaaaaaoAaaaaazo......',
      42: '.oAaaaaoAaaaoAaaaaoAaaaaaoAaaaaazo......',
      43: '..oAaaaoAaaaoAaaaaaoAaaaaaoAaaaazo......',
      44: '.oAaaaaoAaaaoAaaaaaoAaaaaaoAaaaazo......',
      45: '.oAaaaoAaaaaoAaaaaazoAaaaaaoAaaaazo.....',
      46: '.oAaaaoAaaaaoAaaaaaAoAaaaaaoAaaaazo.....',
      47: 'oAaaaaoAaaaaoAaaaaazooAaaaaoAaaaazo.....',
      48: 'oAaaaAoAaaaaoAaaaazo.oAaaaazoAaaazo.....',
      49: 'oAaaazoAaaaaoAaaaazo.oAaaaazooAaaazo....',
      50: 'oAaaazoAaaaaoAaaaaAo.oAaaaazooAaaazo....',
      51: 'oAaaaoAaaaazoAaaaazo..oAaaaazooAaaazo...',
      52: 'oAaaaoAaaazooAaaaazo...oAaaazo.oAaaazo..',
      53: 'oAaazoAaaaAooAaaazo....oAaaazo..oAaazo..',
      54: 'oAaazoAaaazooAaaaAo....oAaaazo...oAaazo.',
      55: 'oAaaoAaaazo.oAaaazo.....oAaaazo...oAaazo',
      56: '....oAaazo.oAaaazo.......oAaazo.........',
      57: '...oAaaAo..oAaazo.........oAaazo........',
      58: '..oAaazo...oAaaAo..........oAaazo.......',
      59: '..........oAaazo........................',
    }));
    K1('dp_talk1', ed(D, {
      0: '...........oWwwwwwwwwbo.................',
      1: '.........oWWWWWWwwwwwwwbo...............',
      2: '.......oWwwwwwwwwwwwbbbbwbo.............',
      3: '......oWwwwWWWWWwwwwwwwwwwbo............',
      4: '.....oWwwwwwwwwwwwwwbbbbwwwbo...........',
      5: '.....oWwwwwWWWWWwwwwwwwwwwwbo...........',
      6: '......oWwwwwwwwwwwwwbbbbwwbo............',
      7: '.......oWwwwwwwwwwwwwwwwwbo.............',
      23: '...oAazooAaaaaaaaaaaaaaazo......oAao3o..',
      33: '...oAaaoAaobbbbbbbbbbbbboaaaaazo.o333o..',
      34: '..oAaaaoAaaoAaaaaoAaaaaoAaaaaaazooYYYo..',
      35: '..oAaaaoAaaoAaaaaoAaaaaoAaaaaaazooyyyo..',
      36: '..oAaaaoAaaoAaaaaoAaaaaoAaaaaaazo.ooo...',
      37: '..oAaaaoAaaoAaaaaoAaaaaaoAaaaaaazo......',
      38: '..oAaaaoAaaoAaaaaaoAaaaaoAaaaaazo.......',
      39: '.oAaaaaoAaaoAaaaaaoAaaaaaoAaaaaazo......',
      40: '.oAaaaoAaaaoAaaaaaaoAaaaaoAaaaaazo......',
      41: '.oAaaaoAaaaoAaaaaaaoAaaaaaoAaaaaazo.....',
      42: 'oAaaaaoAaaaoAaaaaaaoAaaaaaoAaaaaazo.....',
      43: 'oAaaaaoAaaaoAaaaaaazoAaaaaaoAaaaazo.....',
      44: 'oAaaaoAaaaaoAaaaaazo.oAaaaaaoAaaaazo....',
      45: 'oAaaaoAaaaaoAaaaaazo.oAaaaaaoAaaaazo....',
      46: 'oAaaaoAaaaoAaaaaaAo..oAaaaaazoAaaaazo...',
      47: 'oAaaaoAaaaoAaaaaazo...oAaaaazoAaaaazo...',
      48: 'oAaaoAaaaaoAaaaazo.....oAaaaazooAaaazo..',
      49: 'oAaaoAaaaaoAaaaazo.....oAaaaazooAaaazo..',
      50: 'oAaoAaaaazoAaaaaAo......oAaaaazooAaaazo.',
      51: 'oAaoAaaaazoAaaaazo......oAaaaazo.oAaaazo',
      52: 'oAaoAaaazoAaaaazo........oAaaazo.oAaaazo',
      53: 'oAoAaaaAooAaaazo..........oAaaazo.oAaazo',
      54: 'oAoAaaazooAaaaAo..........oAaaazo.oAaazo',
      55: 'ooAaaazo.oAaaazo...........oAaaazooAaazo',
      56: 'oAaazo..oAaaazo..............oAaazo.....',
      57: 'oAaaAo..oAaazo................oAaazo....',
      58: 'oAaazo.oAaaAo..................oAaazo...',
      59: '......oAaazo............................',
    }));
    P.anim('dp_idle', ['dp_idle0', 'dp_idle1'], 3);
    P.anim('dp_talk', ['dp_talk0', 'dp_talk1'], 5);
  }

  /* portraits are 36x40 to match the panel that draws them, anchored at
     the top-left because the panel places them itself */
  const PO = (name, rows) => P.def(name, A(rows, 0, 0));
  /* sharks swim; anchored at the middle so they can be centred on a point */
  const SK = (name, rows) => P.def(name, A(rows, 20, 10));
  const KG = (name, rows) => P.def(name, A(rows, 15, 40));

  /* ---- THE DIALOGUE PORTRAITS ---- */
  function portraits() {
    const _po_king = [
      '.......o..o..o..o..o..o..o..o.......',
      '......oYooYooYooYooYooYooYo.........',
      '.....oGYYoYYoYYoYYoYYoYYoYYGo.......',
      '.....oGYY#YYYY#YYYY#YYYY#YYGo.......',
      '.....ogGGGGGGGGGGGGGGGGGGGgo........',
      '......omNNNNNNNNNNNNNNNNNNNNno......',
      '.....omNNNNNNNNNNNNNNNNNNNNNNno.....',
      '.....oNnKKKKKKKKKKKKKKKKKKKKnNo.....',
      '.....oNnKKKKKKKKKKKKKKKKKKKKnNo.....',
      '.....oNnKKoooKKKKKKKKKKoooKKnNo.....',
      '.....oNnKKoWwwboKKKKKoWwwboKnNo.....',
      '.....oNnKKoWooboKKKKKoWooboKnNo.....',
      '.....oNnKKKKKKKKKKKKKKKKKKKKnNo.....',
      '.....oNnKKKnnnKKkkKKKKnnnKKKnNo.....',
      '.....oNnKKKnnnKoSkoKKKnnnKKKnNo.....',
      '.....oNnKKKKKoqqqqqqqqoKKKKKnNo.....',
      '.....oNnKKKKKKSSSSSSKKKKKKKKnNo.....',
      '.....onnnnnnnnnnnnnnnnnnnnnnnnnno...',
      '....omNNNNNNNNNNNNNNNNNNNNNNNNno....',
      '.....omNNNNNNNNNNNNNNNNNNNNNNno.....',
      '......omNNNNNNNNNNNNNNNNNNNNno......',
      '.......omNNNNNNNNNNNNNNNNNNno.......',
      '........omNNNNNNNNNNNNNNNNno........',
      '....................................',
      '....................................',
      '....................................',
      '..........o%$$$$$$$$$$$$#o..........',
      '......o%$$$$$$$$$$$$$$$$$$$$#o......',
      '..o%$$$$$$$$$$$$$$$$$$$$$$$$$$$$#o..',
      'o%$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#o',
      'o%$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#o',
      '.....oJjjjjjjjjjjjjjjjjjjjjjjho.....',
      '...oJjjjoyyyyyyyyyyyyyyyyyyyojjho...',
      '..oJjjjjoYYYYYYYYYYYYYYYYYYYojjjho..',
      '.oJjjjjjogggggggggggggggggggojjjjho.',
      '.oJjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjho.',
      '.oJjjjjjjjjjjjYjjYjjYjjjjjjjjjjjjho.',
      '.oJjjjjjjjjjjjYjjYjjYjjjjjjjjjjjjho.',
      '.oJjjjjjjjjjjjYYYYYYYjjjjjjjjjjjjho.',
      '.oJjjjjjjjjjjjjjjYjjjjjjjjjjjjjjjho.'
    ];
    PO('po_king', _po_king);
    const _po_queen = [
      '...........oxRRRRRRRRRRro...........',
      '........oxRRRRRRRRRRRRRRRRro........',
      '.....oxRRRRRoRRRRRoRRRRRoRRRRro.....',
      '...oxRRRRRoYWYoRRRRRRoYWYoRRRRRro...',
      '..oxRRRoyYYYWYYYWYYYyoRRRRRRRRRRro..',
      '.......ogGGGGGGGGGGGgo..............',
      '....oRRoxRRRRRRRRRRRRRRRRRRroxxxo...',
      '....oRRRoxRRRRRRRRRRRRRRRRroxxxxo...',
      '....oRRRoKKKKKKKKKKKKKKKKKKoxxxxo...',
      '....oRRRoKKooKKKKKKKKKKooKKoxxxxo...',
      '....oRRRoKKoWwboKKKKKoWwboKoxxxxo...',
      '....oRRRR..oWobo.....oWobo..xxxxo...',
      '....oRRRoKxKKKKKKKKKKKKKKxKoxxxxo...',
      '....oRRRoKKKKKKKKkkKKKKKKKKoxxxxo...',
      '....oRRRoKKKKKKKKKKKKKKKKKKoxxxxo...',
      '....oRRRoKKKKKKKoSkoKKKKKKKoxxxxo...',
      '....oRRRoKKKKKKKKKKKKKKKKKKoxxxxo...',
      '....oRRRoKKKKKKoqqqqoKKKKKKoxxxxo...',
      '....oRRRoKKKKKKKxxxxKKKKKKKoxxxxo...',
      '....oRRRoKKKKKKKKKKKKKKKKKKoxxxxo...',
      '....oRRoKkkkkkkkkkkkkkkkkkkSoxxxo...',
      '....oRRRoKkkkkkkkkkkkkkkkkSoxxxxo...',
      '....oRRRRoKkkkkkkkkkkkkkkSo.xxxxo...',
      '....oRRRR.oKkkkkkkkkkkkkSo..xxxxo...',
      '....oRRRo877777777777777775oxxxxo...',
      '....oo877777777777777777777775oxo...',
      '..o877777777oWWWWWWWWWWWo77777775o..',
      '.o87777777777777777777777777777775o.',
      '.o87777777777777777777777777777775o.',
      '.o87777777777777777777777777777775o.',
      '.o8777777777777oXXo777777777777775o.',
      '.o87777777777777777777777777777775o.',
      '.o87777777777777777777777777777775o.',
      '.o87777777777777777777777777777775o.',
      '.o87777777777777777777777777777775o.',
      '.o87777777777777777777777777777775o.',
      '.o87777777777777777777777777777775o.',
      '.o87777777777777777777777777777775o.',
      '.o87777777777777777777777777777775o.',
      '.o87777777777777777777777777777775o.'
    ];
    PO('po_queen', _po_queen);
    const _po_deep = [
      '..........oWwwwwwwwwwwwwbo..........',
      '.......oWwWWWWWWwwwwwwwwwwwbo.......',
      '....oWwwwwwwwwwwwwwwwbbbbbwwwwbo....',
      '...oWwwwwwwWWWWWWwwwwwwwwwwwwwwbo...',
      '...oWwwwwwwwwwwwwwwwbbbbbwwwwwwbo...',
      '.....oWwwwwwwwwwwwwwwwwwwwwwwbo.....',
      '......owoooooooooooooooooooobo......',
      '.......oAaaaaaaaaaaaaaaaaaazo.......',
      '.....oAaaaaaaaaaaaaaaaaaaaaaazo.....',
      '...oAaaaaaaaaaaaaaaaaaaaaaaaaaazo...',
      '..ooooooooooooooaaaaoooooooooooooo..',
      '.oAoWwwwwwwwwboaaaaaaoWwwwwwwwwbozo.',
      '.oAoWwwWYYYgwboaaaaaaoWwwWYYYgwbozo.',
      '.oAoWwwgooogwboaaaaaaoWwwgooogwbozo.',
      '...oWwwgooogwbo......oWwwgooogwbo...',
      '...oWwwgyyygwbo......oWwwgyyygwbo...',
      '...oWwwgyyygwbo......oWwwgyyygwbo...',
      '...oWwwwwwwwwbo......oWwwwwwwwwbo...',
      '.oAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaazo.',
      '..oAaaaaaaaaaaaaaaaaaaaaaaaaaaaazo..',
      '...oAaaaaaaaaaaaaaaaaaaaaaaaaaazo...',
      '....oAaaaaozzzzzzzzzzzzzzzoaaazo....',
      '......oAaaaazzzzzAzzzzzaaaaazo......',
      '........oAaaaaaaaaaaaaaaaazo........',
      '.....oAaaaaaaaaaaaaaaaaaaaaaazo.....',
      '...oAaaaaaaaaaaaaaaaaaaaaaaaaaazo...',
      '..oAazoaaaaaaaaaaaaaaaaaaaaaaoAazo..',
      '.oAaazoaaaaaaaaaaaaaaaaaaaaaaaoAazo.',
      '.oAaaaaaaaaoWwwwwwwwwwwboaaaaaaaazo.',
      '.oAaaaaaaoWwwwwwwwwwwwwwwboaaaaaazo.',
      '.oAaaaaaoWwwwwwwbwbwwwwwwwboaaaaazo.',
      '.oAaaaaoWwwwwwwwwwwwwwwwwwwboaaaazo.',
      '.oAaaaaoWwwwwwwwwwwwwwwwwwwboaaaazo.',
      '.oAaaaaoWwwwwwwwwwwwwwwwwwwboaaaazo.',
      '.oAaaaaoWwwwwwwwwwwwwwwwwwwboaaaazo.',
      '.oAaaaaoWwwwwwwwwwwwwwwwwwwboaaaazo.',
      '....................................',
      '....................................',
      '....................................',
      '....................................'
    ];
    PO('po_deep', _po_deep);
  }

  /* ---- SHARKS, IN OFF THE BALCONY ---- */
  function sharks() {
    const _sk_swim0 = [
      '...................o....................',
      '..................oJo...................',
      '.................oWJo...................',
      '................oWJJo...................',
      'oJJJJJJo.......ojJJJJo..................',
      '.oJJJJJo......oojjjjjjjjoo..............',
      '..oJJJJo.....oojjjjjjjjjjjjoo...........',
      '...oJJJo..oojjjjjjjjjjjjjjjjjoo.........',
      '....oJJoojjjjjjjjjjjjjjjjjjjjjjoo.......',
      'oJJoJJJojjjjjjjjjjjjjjjjjojojooojJo.....',
      'oJJohhhohhhhhhhhhhhhhhhhhohohooWhhBo....',
      'oBBoBBBoBBBBBBBBBBBBBBBBBBBBoWoWoWo.....',
      '...oJJJo.ooBBBBBBBBBBBBBBBooooBBoo......',
      '..oJJJJo...ooBBBBBBBBBBBoHHHoBoo........',
      '.oJJJJJo.....ooBBBBBBBBoHHoBoo..........',
      'oJJJJJJo.......ooBBBBBBooBoo............',
      '.................ooBBBBBoo..............',
      '..................ooooooo...............',
      '........................................',
      '........................................'
    ];
    SK('sk_swim0', _sk_swim0);
    const _sk_swim1 = [
      '...................o....................',
      '..................oJo...................',
      '.................oWJo...................',
      '................oWJJo...................',
      '...............ojJJJJo..................',
      'oJJJJJJo......oojjjjjjjjoo..............',
      '.oJJJJJo.....oojjjjjjjjjjjjoo...........',
      '..oJJJJo..oojjjjjjjjjjjjjjjjjoo.........',
      '...oJJJoojjjjjjjjjjjjjjjjjjjjjjoo.......',
      'oJJoJJJojjjjjjjjjjjjjjjjjojojooojJo.....',
      'oJJohhhohhhhhhhhhhhhhhhhhohohooWhhBo....',
      'oBBoBBBoBBBBBBBBBBBBBBBBBBBBoWoWoWo.....',
      '..oJJJJo.ooBBBBBBBBBBBBBBBooooBBoo......',
      '.oJJJJJo...ooBBBBBBBBBBBoHHHoBoo........',
      'oJJJJJJo.....ooBBBBBBBBoHHoBoo..........',
      '...............ooBBBBBBooBoo............',
      '.................ooBBBBBoo..............',
      '..................ooooooo...............',
      '........................................',
      '........................................'
    ];
    SK('sk_swim1', _sk_swim1);
    const _sk_swim2 = [
      '...................o....................',
      '..................oJo...................',
      '.................oWJo...................',
      '................oWJJo...................',
      '...............ojJJJJo..................',
      '..............oojjjjjjjjoo..............',
      'oJJJJJJo.....oojjjjjjjjjjjjoo...........',
      '.oJJJJJo..oojjjjjjjjjjjjjjjjjoo.........',
      '..oJJJJoojjjjjjjjjjjjjjjjjjjjjjoo.......',
      'oJJoJJJojjjjjjjjjjjjjjjjjojojooojJo.....',
      'oJJohhhohhhhhhhhhhhhhhhhhohohooWhhBo....',
      'oBooBBBoBBBBBBBBBBBBBBBBBBBBoWoWoWo.....',
      '.oJJJJJo.ooBBBBBBBBBBBBBBBooooBBoo......',
      'oJJJJJJo...ooBBBBBBBBBBBoHHHoBoo........',
      '.............ooBBBBBBBBoHHoBoo..........',
      '...............ooBBBBBBooBoo............',
      '.................ooBBBBBoo..............',
      '..................ooooooo...............',
      '........................................',
      '........................................'
    ];
    SK('sk_swim2', _sk_swim2);
    const _sk_bite = [
      '...................o....................',
      '..................oJo...................',
      '.................oWJo...................',
      '................oWJJo...................',
      '...............ojJJJJo..................',
      'oJJJJJJo......oojjjjjjjjoo..............',
      '.oJJJJJo.....oojjjjjjjjjjjjoo...........',
      '..oJJJJo..oojjjjjjjjjjjjjjjjjoo.........',
      '...oJJJoojjjjjjjjjjjjjjjjjjjjjjoo.......',
      'oJJoJJJojjjjjjjjjjjjjjjjjojojooojJo.....',
      'oJJohhhohhhhhhhhhhhhhhhhhohohoooooBo....',
      'oBBoBBBoBBBBBBBBBBBBBBBBBBBBBoWoWoWo....',
      '..oJJJJo.ooBBBBBBBBBBBBBBBoooooWWWWo....',
      '.oJJJJJo...ooBBBBBBBBBBBoHHHoBoo........',
      'oJJJJJJo.....ooBBBBBBBBoHHoBoo..........',
      '...............ooBBBBBBooBoo............',
      '.................ooBBBBBoo..............',
      '..................ooooooo...............',
      '........................................',
      '........................................'
    ];
    SK('sk_bite', _sk_bite);
    P.anim('sk_swim', ['sk_swim0', 'sk_swim1', 'sk_swim2', 'sk_swim1'], 9);
  }

  /* ---- THE KEG, WHO TEXTS ---- */
  function theKeg() {
    const _kg_idle0 = [
      '..............................',
      '..........o.o.o.o.............',
      '.........oyYYYYYyo............',
      '.........ogGGGGGgoo...........',
      '.......oWWWWWWWWWWWWo.........',
      '.......obWWWWWWWWWWbo.........',
      '.......o43133333133331o.......',
      '.....o431333331333331331o.....',
      '....oVvvvvvvvvvvvvvvvvvvvuo...',
      '...oouuuuuuuuuuuuuuuuuuuuuoo..',
      '..o431333331333331333331331o..',
      '..o43133o3o1o3333o3o3o313331o.',
      '.o431333oWWWo3331oWWWo133331o.',
      '.o431333oWpWo3331oWpWo133331o.',
      '.o4313X33ooo333313ooo31X3331o.',
      '.o43133333133333133333133331o.',
      '.o4313333313oXXXXo3333133331o.',
      '.o43133333133xxxx33333133331o.',
      'ooooo13333313333313333313331o.',
      'oWWWo1333331333331333331331o..',
      'oCCCovvvvvvvvvvvvvvvvvvvvuo...',
      'oWWWo3uuuuuuuuuuuuuuuuuuuuo...',
      'oCCCo3.o431333331333331o..ooo.',
      'oWWWo3...................oYYo.',
      'oCCWo.....................oyo.',
      'oWWWo.....................ooo.',
      'ooooo.........................',
      '..............................',
      '..............................',
      '..............................',
      '..............................',
      '..............................',
      '..............................',
      '..............................',
      '..............................',
      '..............................',
      '..............................',
      '..............................',
      '..............................',
      '..............................'
    ];
    KG('kg_idle0', _kg_idle0);
    const _kg_idle1 = [
      '..............................',
      '..........o.o.o.o.............',
      '.........oyYYYYYyo............',
      '.........ogGGGGGgoo...........',
      '.......oWWWWWWWWWWWWo.........',
      '.......obWWWWWWWWWWbo.........',
      '.......o43133333133331o.......',
      '.....o431333331333331331o.....',
      '....oVvvvvvvvvvvvvvvvvvvvuo...',
      '...oouuuuuuuuuuuuuuuuuuuuuoo..',
      '..o431333331333331333331331o..',
      '..o4313333313333313333313331o.',
      '.o43133333133333133333133331o.',
      '.o431333ooooo3331ooooo133331o.',
      '.o4313X3331333331333331X3331o.',
      '.o43133333133333133333133331o.',
      '.o4313333313oXXXXo3333133331o.',
      'ooooo33333133xxxx33333133331o.',
      'oWWWo13333313333313333313331o.',
      'oCCCo1333331333331333331331o..',
      'oWWWo3vvvvvvvvvvvvvvvvvvvuo...',
      'oCCCo3uuuuuuuuuuuuuuuuuuuuo...',
      'oWWWo3.o431333331333331o..ooo.',
      'oCCWo....................oYYo.',
      'oWWWo.....................oyo.',
      'ooooo.....................ooo.',
      '..............................',
      '..............................',
      '..............................',
      '..............................',
      '..............................',
      '..............................',
      '..............................',
      '..............................',
      '..............................',
      '..............................',
      '..............................',
      '..............................',
      '..............................',
      '..............................'
    ];
    KG('kg_idle1', _kg_idle1);
    P.anim('kg_idle', ['kg_idle0', 'kg_idle1'], 2);
  }

  function build() {
    king(); queenSprite(); theDeep(); portraits(); sharks(); theKeg();
  }
  return { build };
})();
