/* ============================================================
   art/reef.js - the temperate coral ocean: the parallax that
   makes the sea look deep, the reef that makes it beautiful,
   and everything swimming through it.

   Three value families, and they are the whole trick:
     FAR   two shades, DEEP.1 body + DEEP.2 cap. Flat
           silhouettes, no interior detail, no outline. Haze
           eats contrast at distance, so this band must stay
           nearly featureless or the depth illusion dies.
     MID   three shades, DEEP.0 crevice + DEEP.1 + DEEP.2 cap.
           Darker floor, wider range, so it sits in FRONT.
     NEAR  four shades and a near-black INK.0 outline, with a
           DEEP.3 lit rim. Highest contrast in the file.
   The reef itself and the animals break out of that family
   entirely: they are the brightest, most saturated art in the
   game - CORAL, KELP and GOLD, lit from the upper left.

   Everything the engine tiles is authored to wrap:
     bg_far_reef / spires / arch / wreck  tile with themselves
       AND with each other - parallax.js drops them into random
       adjacent slots, so all four are pinned to the same
       silhouette height (row 46) for four columns at each edge.
     bg_mid_coral / bg_mid_rocks  share a band, so both meet
       their edges 12 rows off the bottom.
     bg_mid_kelp, bg_surface, fg_near_kelp, fg_near_coral  wrap
       in x.  bg_shaft, cr_kelp_tall  wrap in y.  fg_silt and
       fg_bubbles wrap in both.
   ============================================================ */
KD.art.reef = (function () {
  const P = KD.PX;

  /* ---- one character table for the whole file, same letters as
     art/actors.js so a colour means the same thing everywhere ----
       o p q P  INK      i d D e E  DEEP (5)     t T c C  WATER
       n N m M  SAND     h H j J  STONE          r R x X  CORAL
       f F + *  KELP     g G y Y  GOLD           u U v V  RUST
       b B w W  BONE     z Z a A  ROT            # $ % &  BLOOD
       1 2 3 4  WOOD     5 6 7 8  CLOTH          s S k K  SKIN
     ------------------------------------------------------------ */
  const C = {
    o: 'INK.0', p: 'INK.1', q: 'INK.2', P: 'INK.3',
    i: 'DEEP.0', d: 'DEEP.1', D: 'DEEP.2', e: 'DEEP.3', E: 'DEEP.4',
    t: 'WATER.0', T: 'WATER.1', c: 'WATER.2', C: 'WATER.3',
    n: 'SAND.0', N: 'SAND.1', m: 'SAND.2', M: 'SAND.3',
    h: 'STONE.0', H: 'STONE.1', j: 'STONE.2', J: 'STONE.3',
    r: 'CORAL.0', R: 'CORAL.1', x: 'CORAL.2', X: 'CORAL.3',
    f: 'KELP.0', F: 'KELP.1', '+': 'KELP.2', '*': 'KELP.3',
    g: 'GOLD.0', G: 'GOLD.1', y: 'GOLD.2', Y: 'GOLD.3',
    u: 'RUST.0', U: 'RUST.1', v: 'RUST.2', V: 'RUST.3',
    b: 'BONE.0', B: 'BONE.1', w: 'BONE.2', W: 'WHITE',
    z: 'ROT.0', Z: 'ROT.1', a: 'ROT.2', A: 'ROT.3',
    s: 'SKIN.0', S: 'SKIN.1', k: 'SKIN.2', K: 'SKIN.3',
    '#': 'BLOOD.0', '$': 'BLOOD.1', '%': 'BLOOD.2', '&': 'BLOOD.3',
    1: 'WOOD.0', 2: 'WOOD.1', 3: 'WOOD.2', 4: 'WOOD.3',
    5: 'CLOTH.0', 6: 'CLOTH.1', 7: 'CLOTH.2', 8: 'CLOTH.3'
  };

  const D = (name, px, ax, ay) => P.def(name, { pal: C, ax: ax || 0, ay: ay || 0, px: px });

  function build() {
    /* ==========================================================
       A. PARALLAX BACKDROPS
       ========================================================== */
    /* --- A.1 tiling silhouette plates ------------------------ */
    D('bg_far_reef', [
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '..............................................................HHHH..............................',
      '.............................................................HHHHHH.............................',
      '............................................................HHhhhhHH............................',
      '...........................................................HHhhhhhhHH...........................',
      '..........................................................HHhhhhhhhhh...........................',
      '...................................................HHHHH..hhhhhhhhhhhH..........................',
      '...............HHH.................................hHHHh.Hhhhhhhhhhhhh..........................',
      '..............HHHHH................................hhhhh.hhhhhhhhhhhhhH.........................',
      '.............HHhhhHH.................HHH......HHHHHhhhhhHhhhhhhhhhhhhhh..........HHHH...........',
      '.............hhhhhhHH.HHHHH.........HHHHH.....hHHHhhhhhhhhhhhhhhhhhhhhh.........HHHHHH..........',
      '............HhhhhhhhHHHHHHh.........hhhhHH....hhhhhhhhhhhhhhhhhhhhhhhhh........HHhhhhHH.........',
      '............hhhhhhhhhHhhhhhHH......Hhhhhhh....hhhhhhhhhhhhhhhhhhhhhhhhh.......HHhhhhhhh.........',
      '...........HhhhhhhhhhhhhhhhhHH.....hhhhhhhH...hhhhhhhhhhhhhhhhhhhhhhhhh...HHHHHhhhhhhhhH........',
      '.........HHhhhhhhhhhhhhhhhhhhh....HhhhhhhhhHHHhhhhhhhhhhhhhhhhhhhhhhhhhHHHHHHHhhhhhhhhhh........',
      '......HHHHHhhhhhhhhhhhhhhhhhhh....hhhhhhhhhHHhhhhhhhhhhhhhhhhhhhhhhhhhhhHHhhhhhhhhhhhhhhH.......',
      '......hHHhhhhhhhhhhhhhhhhhhhhhH...hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh.......',
      'HHHHHHhhhhhhhhhhhhhhhhhhhhhhhhhHHHhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhHHHHHHH',
      'HHHHHhhhhhhhhhhhhhhhhhhhhhhhhhhHHhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhHHHHHH',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh'
    ]);
    D('bg_far_spires', [
      '................................................................................................',
      '................................................................................................',
      '..................................................HHH...........................................',
      '.................................................Hhh............................................',
      '.................................................Hhh............................................',
      '.................................................Hhh............................................',
      '.................................................Hhh............................................',
      '.................................................Hhh............................................',
      '................................................Hhhhh...........................................',
      '...............................................Hhhhh...........HHHHH............................',
      '...............................................Hhhhh............Hhhhh...........................',
      '...............................................Hhhhh............Hhhhh...........................',
      '...............................................Hhhhh............Hhhhh...........HHH.............',
      '..............HHHHHHH..........................Hhhhh............Hhhhh..........Hhh..............',
      '.............HhhhhHHH..........................Hhhhh............Hhhhh..........Hhh..............',
      '.............HhhhhhHhh.........................Hhhhh...........Hhhhhhh.........Hhh..............',
      '.............HhhhhhHhh.........................Hhhhh............Hhhhhhh........Hhh..............',
      '.............HhhhhhHhh........................HhhHHHHH..........Hhhhhhh........Hhh..............',
      '............HhhhhhhHhh.......................HhhhhHhhhh.........Hhhhhhh........Hhh..............',
      '...........HhhhhhhhHhh.......................HhhhhHhhhh.........Hhhhhhh.......Hhhhh.............',
      '...........HhhhhhhhHhh.......................HhhhhHhhhh.........Hhhhhhh......Hhhhh..............',
      '...........HhhhhhhhHhh.......................HhhhhHhhhh.........Hhhhhhh......Hhhhh..............',
      '...........HhhhhhhhHhh.......................HhhhHhhhhhh.......Hhhhhhhhh.....Hhhhh..............',
      '...........HhhhhhhhHhh.......................HhhhhHhhhhhh.......Hhhhhhhhh....Hhhhh..............',
      '..........HhhhhhhhhHhh.......................HhhhhHhhhhhh.......Hhhhhhhhh....Hhhhh..............',
      '.........HhhhhhhhhHhhhh.....................HhhhhhHhhhhhh.......Hhhhhhhhh....Hhhhh..............',
      '.........HhhhhhhhhhHhhhh.....HHHHH.........HhhhhhhHhhhhhh.......Hhhhhhhhh....Hhhhh..............',
      '.........HhhhhhhhhhHhhhh.....Hhhhh.........HhhhhhhHhhhhhh.......Hhhhhhhhh...Hhhhhhh.HHH.........',
      '.........HhhhhhhhhhHhhhh.....Hhhhh.........HhhhhhhHhhhhhh.......Hhhhhhhhh..Hhhhhhh..Hhh.........',
      '.........HhhhhhhhhhHhhhh.....Hhhhh.........HhhhhhHhhhhhhhh.....Hhhhhhhhhhh.Hhhhhhh..Hhh.........',
      'HHHHHH..HhhhhhhhhhhHhhhh..HHHhhhhhh........HhhhhhhHhhhhhhhh.....HhhhhhhhhhhHhhhhhh..Hhh...HHHHHH',
      'HHHHHh.HhhhhhhhhhhhHhhhh..hHHhhhhhh.......HhhhhhhhHhhhhhhhh.....HhhhhhhhhhhHhhhhhh.HhhhhHHHHHHHH',
      'hhhhhhHHhhhhhhhhhhhHhhhhHHhhHhhhhhh......HhhhhhhhhHhhhhhhhh.HHHHHhhhhhhhhhhHhhhhhh.HhhhhHHhhhhhh',
      'hhhhhhhHhhhhhhhhhhhHhhhhHhhhHhhhhhhHHHHHHHhhhhhhhhHhhhhhhhhHHHHHHhhhhhhhhhhHhhhhhhHHhhhhhhhhhhhh',
      'hhhhhhhHhhhhhhhhhhhhHhhhhhhhHhhhhhhhHHHHHHhhhhhhhhHhhhhhhhhHhhhhHhhhhhhhhhhhhhhhHHHHhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh'
    ]);
    D('bg_far_arch', [
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '....................................HHHHHHHHHH..................................................',
      '....................................hhhhhhhhhhH.................................................',
      '...............................HHHHHhhhhhhhhhhh...HHHHHHHH......................................',
      '...............................hhhhhhhhhhhhhhhhH..hhhhhhhh......................................',
      '..........................HHHHHhhhhhhhhhhhhhhhhh.Hhhhhhhhh......................................',
      '....................HHHHHHhhhhhhhhhhhhhhhhhhhhhhhhhhhhhHHHHHHHHH................................',
      '....................hhhhhhhhhhhhhhhhhhhhhhhhh.hhhhhhhhhhhhhhhhhh................................',
      '....................hhhhhhhhhhhhhhhhhhh.........hhhhhhhhhhhhhhhh................................',
      '....................hhhhhhhhhhhhhhhhhhh.........hhhhhhhhhhhhhhhh................................',
      '....................hhhhhhhhhhhhhh.....................hhhhhhhhhHHHHHHHHHHH.....................',
      '....................hhhhhhhhhhhhhh.....................hhhhhhhhhhhhhhhhhhhh.....................',
      '....................hhhhhhhhhhhh.......................hhhhhhhhhhhhhhhhhhhh.....................',
      '...................HhhhhhhhhhhhhH.............................hhhhhhhhhhhhh.....................',
      '...................hhhhhhhhhhhhhh.............................hhhhhhhhhhhhh.....................',
      '...................hhhhhhhhhhhhhh.............................hhhhhhhhhhhhh.....................',
      '...................hhhhhhhhhhhhhh.............................hhhhhhhhhhhhh.....................',
      '...................hhhhhhhhhhhhhh............................HhhhhhhhhhhhhhH....................',
      '...................hhhhhhhhhhhhhh............................hhhhhhhhhhhhhhh....................',
      '...................hhhhhhhhhhhhhh............................hhhhhhhhhhhhhhh....................',
      '...................hhhhhhhhhhhhhh............................hhhhhhhhhhhhhhh....................',
      '.................HHhhhhhhhhhhhhhhHH.....HHHHHHHHHHHHH........hhhhhhhhhhhhhhh....................',
      '.................hhhhhhhhhhhhhhhhhh.....hhhhhhhhhhhhh........hhhhhhhhhhhhhhh....................',
      '.................hhhhhhhhhhhhhhhhhhHHHHHhhhhhhhhhhhhh......HHhhhhhhhhhhhhhhhHH..................',
      '.................hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhHHHHHHhhhhhhhhhhhhhhhhhhh..................',
      'HHHHHH...........hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh............HHHHHH',
      'HHHHHHHHHHH......hhhhhhhhhhhhhhhhhhhhhhh.......hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh......HHHHHHHHHHHH',
      'hhhhhhHHHHHHHHHHHhhhhhhhhhhhhhhhhhhHHHH.....HHHhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhHHHHHHHHHHHHhhhhhh',
      'hhhhhhhhhhhHHHHHHhhhhhhhhhhhhhhhhhhHHHHHHHHHHHHHHHhhhhhhhhhhhhhhhhhhhhhhhhhhhhHHHHHHhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhHHHHHhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh'
    ]);
    D('bg_far_wreck', [
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '............................................................u...................................',
      '...........................................................u....................................',
      '...........................................................u....................................',
      '......................................................uuuuuuuuuu................................',
      '.........................................................u......................................',
      '.........................................................u......................................',
      '........................................................u..............................u........',
      '........................................u...............u.............................uu........',
      '.......................................u.......uuuuuuuuuuuuuuuuuu....................uu.........',
      '.......................................u.......uuuuuuuuuuuuuuuuuu...................uu..........',
      '......................................u...............uu...........................uu...........',
      '......................................u..............uu...........................uu............',
      '.....................................u..............uu...........................uu.............',
      '..............................uuuuuuuuuuuuuuu.......uu.....................UUUUUuu..............',
      '..............................uuuuuuuuuuuuuuu......uu......................uuuuuu...............',
      '...................................uu.........UUUUUuuUUUU..................uuuuuu...............',
      '.....................U............uu..........uuuuuuuuuuu..........UUUUUUUUuuuuuu...............',
      '.................U...u............uu..........uuuuuuuuuuu..........uuuuuuuuuuuuuu...............',
      '.................u...uU..........uu...........uuuuuuuuuuuUUUUUUUUUUuuuuuuuuuuuuuu...............',
      '.................u..uuu..........uu..UUUUUUUUUuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu...............',
      '.................u.uuuuUUUUUUUUUuuUUUuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu...............',
      '...............U.uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu...............',
      '...............u.uuUuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu...............',
      '...............uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu...............',
      '...............uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu...............',
      '..............uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu...............',
      'UUUUUU........uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu...UUUUUUUUUUUU',
      'UUUUUu........uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuUUUUUUUUUUUUUUU',
      'uuuuuuUUUUU...uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuUUUuuuuuuuuuuuu',
      'uuuuuuuUUUUUUUuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuUUUuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
      'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu'
    ]);
    D('bg_mid_kelp', [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '.......................F........................................',
      '.......................FF.......................................',
      '.......................FF.......................................',
      '.......................FF.......................................',
      '.......................FF.......................................',
      '.......................FF.......................................',
      '..........F............FF.......................................',
      '..........FF............FFF.....................................',
      '..........FF............FF.FF...............f...................',
      '..........FF............FF.FF...............ff..................',
      '..........FF............FF.FF...............fff.................',
      '..........FF............FF.FF...............fff.................',
      '..........FF............FF.FF...............fff...........f.....',
      '.........FFF............FF.FF...............fff...........ff....',
      '.........FF.FF..........FF.FF...............fff...........fff...',
      '.........FF.FF..........FF.FF................ffff.........fff...',
      '.........FF.FF..........FF.FF.f..............fff.ff.......fff...',
      '.........FF.FF.........FFF.FF.ff.............fff.ff.......fff...',
      '.........FF.FF.......FF..FFFF.fff............fff.ff.......fff...',
      '.........FF.FF......FF...FFFF.fff............fff.ff......ffff...',
      '...F.....FF.FF......FF...FF.F.fff............fff.ff......fff.ff.',
      '...FF....FF.FF......FF...FF.F.fff............fff.ff......fff.ff.',
      '...FF....FF..F......FF...FF...fff............fff.ff......fff.ff.',
      '...FF...FFF..F......FF...FF..ffff............fff.ff......fff.ff.',
      '...FF.FFFF..........FF...FF..fff.ff..........fff.ffF.....fff.ff.',
      '...FFFF.FF..........FF...FF..fff.ff.........ffff.ffFF....fff.ff.',
      '...FFFF.FF..........FF...FF..fff.ff.......ff..fffffFF....fff.ff.',
      '....FFF.FF..........FF...FFF.fff.ff......ff...fffffFF....fff.ff.',
      '....FFFFFF......f...FF...FF.Ffff.ff......ff...fff.fFF....fff.ff.',
      '....FFFFFF......ff..FF...FF.Ffff.ff......ff...fff.fFF...ffff.ff.',
      '....FFFFFF......fff.F....FF.Ffff.ff......ff...fff..FF.fffff..ff.',
      '....FFFFFF......fff.F....FF.Ffff.ff......ff...fff...Fff.fff..ff.',
      '....FF.FFF......fff......FF.Ffff.ff......ff...fff...FffFfff...f.',
      '....FF.FFFF.....fff......FF.ffff.ff......ff...fff...FffFfff...f.',
      '....FF.FFF.FF...fff......Ffffff..ff..F...ff...fff...FffFfff.....',
      '....FF.FFF.FF....ffff....ff.fff..ff..FF..ff...ffff..FffFfff.....',
      '....FF..FF.FF....fff.ff..ff.fff...f..FF..ff...fff.ffFffFfff.....',
      '...FFF..FF.FF....fff.ff.Fff.fff...f..FF..ff...fff.ffFffFfff.....',
      '.FF..FF.FF.FF....fff.fFF.ff.fff......FF..f....fff.ffFffFfff....F',
      'FF...FF.FF.FF....fff.FF..ff.fff......FF..f....fff.ffFffFffff...F',
      'FF...FF.FF.FF....fff.FF..ff.fff......FF.......fff.ffFffFfff.ff.F',
      'FF...FF.FF.FF....fff.FF..ff.fff.....FFF.......fff.fFFffFfff.ff.F',
      'FF...FF.FF..F....fff.FF..ff.fff.....FF.FF.....fffFFf.fFFfff.ff.F',
      'FF...FFFFF..F....fff.FF..ff.ffff....FF.FF.....ffFFff.fFFfff.ff.F',
      'FF...FF.FF.......fff.FF..ff.fff.ff..FF.FF.....ffFFff.FF.fff.ff.F',
      'FFF.FFF.FF......ffff.FF..ff.fff.ff..FF.FF....fffFFff.FF.fff.ff..',
      'FF.FFFF.FF....ff..fffFF..fF.fff.ff..FF.FF..ff.ffFFff.FF.fff.ff..',
      'FF.FFFFFFF...ff...fffFF..fFFfff.ff..FF.FF.ff..ffFFff.FF.fff.ff..',
      'FF.FFFF.FF...ff...fffFF..FF.fff.ff..FF.FF.ff..ffFF.f.FF.fff.ff..',
      'FF.FFFF.FF...ff...fffFF..FF.fff.ff..FF.FF.ff..ffFF.f.FFffff.ff..',
      'FF.FFFF.FF...ff...fffF...FF.fff.ff..FF.FF.ff..ffFF...ff.fff.ff..',
      'FF.FFFF.FF...ff...fffF...FF.fff.ff.FFF.FF.ff..ffFF..ffFFfff.ff..',
      'FF..FFF.FF...ff...fff....FF.fff.fFFFF..FF.ff..ffFF..ffF.fff..f..',
      'FF..FFF.FFF..ff...fff....FFffff.FF.FF..FF.ff..ffFF..ffF.fff..f..',
      'FF...FF.FF.FFff...fff....ff.fff.FF.FF...F.ff..ffF...ffF.fff.....',
      'FF...FF.FF.FFff...ffff..ffF.fff.FF.FF...F.ff..ffFf..ffF.fff....F',
      '.FF..FF.FF.FFff...fff.ffffF.fff.FF.FF.....ff..fff.ffffF.fff..FF.',
      '.FF.FFF.FF.FFff...fff.fFff..fff.FF.FF.....ff..fff.ffffF.fff.FF..',
      '.FFF.FF.FF.FFf....fffFFfff..fff.FF.FF.....f...fff.ffffF.fff.FF..',
      '.FF..FF.FF.FFf....ffFFffff..fff.FF.FF.....f...fff.ffffF.ffffFF..',
      '.FF..FF.FF.FF.....ffFFffff..fff.FF.FF.........fff.ffffF.fff.FF..',
      '.FF..FF.FF.FF.....ffFFffff..fff.FF.FFF........fff.ffffF.fff.FF..',
      '.FF..FF.FF..F.....ffFFffff..fff.FF.FF.FF......fff.FFfFF.fff.Ff..',
      '.FF..FF.FFF.F.....ffFFffff..ffffFF.FF.FF......fffFFffFF.fff.Ff..',
      '.FF..FFF.FF.......ffFFffff..fff.Ff.FF.FF......fffFFf.FF.fff.ff..',
      '.FFF.FF..FF......fffFFffff..fff.Ff.FF.FF....ffff.FFf.FF.fff.ff..',
      '.FF.FFF..FF....ff.ffFFfffF..fff.ff.FF.FF..ff.fff.FFf.FF.fff.ff..',
      '.FF.FFFF.FF...ff..ffFFfffFF.fff.ff.FF.FF.ff..fff.FFf.FF.fff.ff..',
      '.FF.FFF.FFF...ff..ffFF.FF..Ffff.ff.FF.FF.ff..fff.FFf.FF.fff.ff..',
      '.FF.FFF.FFF...ff..ffFF.FF..Ffff.ff.FF.FF.ff..fff.FFf.FF.ffffff..',
      '.FF.FFF.FFF...ff..ffF..FF..Ffff.ff.FF.FF.ff..fff.FF..Fff.fffff..',
      '.FF.FFF.FFF...ff..ffF..FF..Ffff.ffFFF.FF.ff..fff.FF..ffF.fffff..',
      '.FF..FF.FFF...ff..fff..FF..Ffff.FF.FF.FF.ff..fff.FF..ff.Ffff.f..',
      '.FF..FF.FFFF..ff..fff..FF..FfffFFf.FF.FF.ff..fff.FF..ff.Ffff.f..',
      '.FF..FF.FFFFFFff..fff..FF.ffFffFFf.FF..F.ff..fff.F...ff.Ffff....',
      'FFF..FF.FFFFFFff..ffff.FFffFFffFFf.FF..F.ff..ffffF...ff.Ffff....',
      '.FF..FF..FFFFFff..fff.fFFffFFffFFf.FF....ff.fff..ff..ff.Ffff..FF',
      '.FFFFF...FFFFFff..fffFFF.ffFFffFFf.FF....ff.fff..ff..ff.Ffff.FF.',
      '.FF.FF....FFFFf...fFF.FF.ffFFffFF..FF....f..fff..ff..ff.Ffff.FF.',
      'FFF.FF....FFFFf...FFf.FF.ffFFffFF..FF....f..fff..ff..ff.FffffFF.',
      'FFF.FF....FFFF....FFf.FF.ff.FffFF..FF.......fff..ff..ff.FFfffFF.',
      'FFF.FF....FFFF....FFf.FF.ff.FffFF..FFF......fff..ffFFff.FFfffFF.',
      'FFF.FF....FF.F....FFf.FF.ff..ffFF..FF.FF....fff..FF.Ff..FFfffFf.',
      'FFF.FF....FFFF....FFf.FF.ff..ffFF..FF.FF....fff.FFf.Ff..FFfffFf.'
    ]);
    D('bg_mid_coral', [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '...........................RRR..................................',
      '..........................RRRRR.................................',
      '..........................rrrrRR................................',
      '.........................Rrrrrrr................................',
      '.........................rrrrrrrRR..............................',
      '......................RoRrrrrrrrrr..............................',
      '......................rorrrrrrrrrr..............................',
      '......................rorrrrrrrrrrRR........RRR.................',
      '....................RRrorrrrrrrrrrrr........rRr.................',
      '....................rrrorrrrrrrrrrro......RRrrrR................',
      '....................rrrorrrrrrrrrrro......rrrrrr................',
      '....................rrrorrrrrrrrrrrooo..RRrrrrrrR...............',
      '..................RRrrrorrrrrrrrrrrooo..rrrrrrrrr...............',
      '..................rrrrrorrrrrrrrrrrooo..rrrrrrrrr...............',
      '..................rrrrrorrrrrrrrrrroooRRrrrrrrrrr...............',
      '.......RRR........rrrrrorrrrrrrrrrrooorrrrrrrrrrr.......R.......',
      '.......rRr......RRrrrrrorrrrrrrrrrrooorrrrrrrrrrrRR....RRR......',
      '......RrrrRRRR..rrrrrrrorrrrrrrrrrrooorrrrrrrrrrrrr..RRRrr......',
      '......rrrrrRRRRoorrrrrrorrrrrrrrrrrooorrrrrrrrrrrrrooRRrrrR.....',
      '.....RrrrrrrrrRoorrrrrrorrrrrrrrrrrooorrrrrrrrrrrrroorrrrrr.....',
      '.....rrrrrrrrrroorrrrrrrorrrrrrrrrrooorrrrrrrrrrrrroorrrrrr.....',
      '.....rrrrrrrrrroorrrrrrrorrrrrrrrrrooorrrrrrrrrrrrroorrrrrr.....',
      '....RrrrrrrrrrroorrrrrrrorrrrrrrrrrooorrrrrrrrrrrrroorrrrrrR....',
      '....rrrrrrrrrrroorrrrrrrorrrrrrrrrrooorrrrrrrrrrrrroorrrrrrr....',
      'RRRRrrrrrrrrrrroorrrrrrrorrrrrrrrrrooorrrrrrrrrrrrroorrrrrrrRRRR',
      'RRRrrrrrrrrrrrroorrrrrrrorrrrrrrrrrrooorrrrrrrrrrrroorrrrrrrrRRR',
      'rrrrrrrrrrrrrrroorrrrrrrorrrrrrrrrrrooorrrrrrrrrrrroorrrrrrrrrrr',
      'rrrrrrrrrrrrrrroorrrrrrrorrrrrrrrrrrooorrrrrrrrrrrroorrrrrrrrrrr',
      'rrrrrrrrrrrrrrroorrrrrrrorrrrrrrrrrrooorrrrrrrrrrrroorrrrrrrrrrr',
      'rrrrrrrrrrrrrrroorrrrrrrorrrrrrrrrrrooorrrrrrrrrrrroorrrrrrrrrrr',
      'rrrrrrrrrrrrrrroorrrrrrrorrrrrrrrrrrooorrrrrrrrrrrroorrrrrrrrrrr',
      'rrrrrrrrrrrrrrroorrrrrrrorrrrrrrrrrrooorrrrrrrrrrrrroorrrrrrrrrr',
      'rrrrrrrrrrrrrrroorrrrrrrorrrrrrrrrrrooorrrrrrrrrrrrroorrrrrrrrrr',
      'rrrrrrrroorrrrroorrroorrorrrrrrroorrooorrrrroorrrrrroorroorrrrrr',
      'rroorrrrooorrroooorrooororoorrrroooroooorrrrooorrroooorrooorrroo',
      'roooorroooooroooooroooooooooorroooooooooorrooooorooooorooooorooo',
      'oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo',
      'oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo',
      'oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo',
      'oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo',
      'oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo',
      'oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo',
      'oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo',
      'oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo',
      'oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo',
      'oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo'
    ]);
    D('bg_mid_rocks', [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '..................HHHHHHHHHHHHHHH...............................',
      '..................HHHHHHHHHHHHHHh...............................',
      '.................HHHHHHHHhhhhhhhhH..............................',
      '.................Hhhhhhhhhhhhhhhhh..............................',
      '................HHhhhhhhhhhhhhhhhhH.............................',
      '................Hhhhhhhhhhhhhhhhhhh.............................',
      '..............HHHhhhhhhhhhhhhhhhhhhH.........HHHHHHHHHH.........',
      '..............HHhhhhhhhhhhhhhhhhhhhh.........HHHHHHHHHh.........',
      '.............HHHhhhhhhhhhhhhhhhhhhhhH.......HHHHHHhhhhhH........',
      '.............Hhhhhhhhhhhhhhhhhhhhhhho.......Hhhhhhhhhhhh........',
      '.......HHHHHHHhhhhhhhhhhhhhhhhhhhhhhoH.....HHhhhhhhhhhhhHH......',
      '.......HHHHHHhhhhhhhhhhhhhhhhhhhhhhhoo.....Hhhhhhhhhhhhhho......',
      '.....HHHHHhhHhhhhhhhhhhhhhhhHHHHHhhhooH..HHHhhhhhhhhhhhhhoH.....',
      '.....HHhhhhhhhhhhhhhhhhhhhhhhhhhhhhhooo..HHhhhhhhhhhhHHHHHo.....',
      '....HHHhhhhhhhhhhhhhhhhhhhhHhhhhhHhhoooHHHHhhhhhhhhhhhhhhhoH....',
      '....HhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhooooHhhhhhhhhhhhHhhhhhoo....',
      '....HhhhhhhhhhhhhhhhhhhhhhHhhhhhhhHhhoooHhhhhhhhhhhhHhhhhhoo....',
      '....hhhhhhhhhhhhhhhhhhhhhhHhhhhhhhhhhooohhhhhhhhhhhHhhhhhhHo....',
      'HHHHhhhhhhhhhhhhhhhhhhhhhHhhhhhhhhhhhhoohhhhhhhhhhhHhhhhhhhoHHHH',
      'HHHhhhhhhhhhhhhhhhhhhhhhhHhhhhhhhhhhhhoohhhhhhhhhhhhhhhhhhhHhHHH',
      'hhhhhhhhhhhhhhhhhhhhhhhhHhhhhhhhhhhHHhhohhhhhhhhhhHhhhhhhhhoHhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhHhhhhhhhhhhoohhohhhhhhhhhhHhhhhhhhhoohhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhoohhhhhhhhhhhhhhhhhhhhhhoohhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhoohhhhhhhhhhhhhhhhhhhhhhoohhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhoohhhhhhhhhhhhhhhhhhhhhhoohhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhoohhhhhhhhhhhhhhhhhhhhhhoohhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhoohhhhhhhhhhhhhhhhhhhhhhoohhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhoohhhhhhhhhhhhhhhhhhhhhhoohhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhoohhhhhhhhhhhhhhhhhhhhhhoohhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhoohhhhhhhhhhhhhhhhhhhhhhoohhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhoohhhhhhhhhhhhhhhhhhhhhhoohhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhoohhhhhhhhhhhhhhhhhhhhhhoohhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhoohhhhhhhhhhhhhhhhhhhhhhoohhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhoohhhhhhhhhhhhhhhhhhhhhhoohhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhoohhhhhhhhhhhhhhhhhhhhhhoohhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhoohhhhhhhhhhhhhhhhhhhhhhoohhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhoohhhhhhhhhhhhhhhhhhhhhhoohhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhoohhhhhhhhhhhhhhhhhhhhhhoohhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhoohhhhhhhhhhhhhhhhhhhhhhoohhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhoohhhhhhhhhhhhhhhhhhhhhhoohhh'
    ]);
    D('bg_mid_school', [
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '..................BB....BB......................',
      '.................BB....BB.......................',
      '.............bb....BBBbbbb....BB................',
      '............bb..BBBBbb.bb....BB.................',
      '.........BB...wBBBBbb....BbbBBBB....BB..........',
      '........BB...wbBB.BB....BbBB.BB....BB...........',
      '..........bBBBBB.BB..BBbbBB....BBBbBB....ww.....',
      '......BB.bBBBBB....wBbbBBB....BBB.BB....ww......',
      '.....BB...BBBB..wwwBbb.BB..bbBB.....bb.BBB......',
      '.......BBBBB..BwBBbBB....wbbBBbb...bbB.BB....BB.',
      '....wwBBBbbb.BBBB.BB....wBBB.bb....BB....bb.BB..',
      '...ww...bbb.BBbb.BB..BBbbBB....wbbBBB...bbB.....',
      '.....BB.BBBBBBB....BBbbBBB....wbBBBB....BB......',
      '....BBBB.BbBBBB...BBbb.BB....bbBB...bb.BB.......',
      '.....BB...BBBB..BBBww....BBBBBBB...bbB..........',
      '.......ww.BB..BBBbBB....BBBB.BB....BB...........',
      '......ww.BB..BBbbBB..BBbbBB....bb.BB............',
      '........BB....bb...BBBBBww....bb................',
      '..........BBBBB...BBBB.ww....BB.................',
      '.........BBBBB....bbB...BBB.bb..................',
      '..............wBBbb....BBB......................',
      '.............wBB...BB.ww........................',
      '..................BB............................',
      '................................................',
      '................................................',
      '................................................',
      '................................................'
    ]);
    D('bg_shaft', [
      't...c.c...C.C.C.C.C.C.c.c...t...',
      '...t...c.C.C.C.C.C.C.C...c......',
      '....c.c...C.C.C.C.C.C.c.c..t....',
      '..t....c.C.C.C.C.C.C.C...c....t.',
      '....c.c...C.C.C.C.C.C.c.c.......',
      '.t.....c.C.C.C.C.C.C.C...c...t..',
      '....c.c...C.C.C.C.C.C.c.c.......',
      't......c.C.C.C.C.C.C.C...c..t...',
      '...tc.c...C.C.C.C.C.C.c.c.......',
      '.......c.C.C.C.C.C.C.C...c.t....',
      '..t.c.c...C.C.C.C.C.C.c.c.....t.',
      '.......c.C.C.C.C.C.C.C...c......',
      '.t....c...C.C.C.C.C.C.c.c....t..',
      '....t..c.c.C.C.C.C.C.c...c......',
      '......c...C.C.C.C.C.C.c.c...t...',
      '...t...c.c.C.C.C.C.C.c...c......',
      '......c...C.C.C.C.C.C.c.c..t....',
      '..t....c.c.C.C.C.C.C.c...c......',
      '......c...C.C.C.C.C.C.c.c.t.....',
      '.t.....c.c.C.C.C.C.C.c...c...t..',
      '....t.c...C.C.C.C.C.C.c.c.......',
      '.......c.c.C.C.C.C.C.c...c..t...',
      '...t..c...C.C.C.C.C.C.c.c.......',
      '.......c.c.C.C.C.C.C.c...c.t....',
      '..t...c...C.C.C.C.C.C.c.c.......',
      '.....t.c.c.C.C.C.C.C.c....t.....',
      '......c...C.C.C.C.C.C.c.c.......',
      '....t..c.c.C.C.C.C.C.c...t......',
      '......c...C.C.C.C.C.C.c.c...t...',
      '...t...c.c.C.C.C.C.C.c..........',
      '......c...C.C.C.C.C.C.c.c..t....',
      '..t....c.c.C.C.C.C.C.c..........',
      '.....tc...C.C.C.C.C.C.c.c.t.....',
      '.......c.c.C.C.C.C.C.c..........',
      '....t.c...C.C.C.C.C.C.c.ct......',
      '.......c.c.C.C.C.C.C.c......t...',
      '...t..c...C.C.C.C.C.C.c.c.......',
      '.......c.c.C.C.C.C.C.c.....t....',
      '......c...C.C.C.C.C.C.c.c.......',
      '.....t.c.c.C.C.C.C.C.c....t.....',
      '..........c.C.C.C.C.C.c.c.......',
      '....t..c.c.C.C.C.C.C.C...c......',
      '..........c.C.C.C.C.C.c.c...t...',
      '.......c.c.C.C.C.C.C.C...c......',
      '......t...c.C.C.C.C.C.c.c..t....',
      '.......c.c.C.C.C.C.C.C...c......',
      '.....t....c.C.C.C.C.C.c.c.t.....',
      '.......c.c.C.C.C.C.C.C...c......',
      '..........c.C.C.C.C.C.c.ct......',
      '.......t.c...C.C.C.C.c..........',
      '..........c.C.C.C.C.C.c.c.......',
      '......t..c...C.C.C.C.c.....t....',
      '..........c.C.C.C.C.C.c.c.......',
      '.....t...c...C.C.C.C.c....t.....',
      '..........c.C.C.C.C.C.c.c.......',
      '.........c...C.C.C.C.c...t......',
      '.......t..c.C.C.C.C.C.c.c.......',
      '.........c...C.C.C.C.c..........',
      '......t...c.C.C.C.C.C.c.c..t....',
      '.........c...C.C.C.C.c..........',
      '..........c.C.C.C.C.C.c...t.....',
      '........tc...C.C.C.C.c..........',
      '..........c.C.C.C.C.C.c..t......',
      '.......t.c...C.C.C.C.c..........',
      '..........c.C.C.C.C.C.c.t.......',
      '......t..c...C.C.C.C.c..........',
      '..........c.C.C.C.C.C.c.........',
      '.........c...C.C.C.C.c....t.....',
      '........t.c.C.C.C.C.C.c.........',
      '.........c...C.C.C.C.c...t......',
      '.......t..c.C.C.C.C.C.c.........',
      '.........c...C.C.C.C.c..t.......',
      '..........c.c.C.C.C...c.........',
      '.........t...C.C.C.C.c.t........',
      '..........c.c.C.C.C...c.........',
      '........t....C.C.C.C.c..........',
      '..........c.c.C.C.C...c..t......',
      '.......t.....C.C.C.C.c..........',
      '..........c.c.C.C.C...c.t.......',
      '.............C.C.C.C.c..........',
      '.........t..c.C.C.C.C.c.........',
      '.............c.C.C.C.c....t.....',
      '........t...c.C.C.C.C.c.........',
      '................................',
      '..............C.C.C.C...........',
      '................................',
      '..............C.C.C.C...........',
      '................................',
      '..............C.C.C.C...........',
      '................................',
      '................................',
      '................................',
      '................C.C.............',
      '................................',
      '................................',
      '................................'
    ]);
    D('fg_near_kelp', [
      '................................',
      '................................',
      '......+.........................',
      '......+F........................',
      '......+Ffo......................',
      '......+Ffo......................',
      '......FFfo......................',
      '......+Ffo......................',
      '.......+Ffo.....................',
      '.......+Ffo.....................',
      '.......+Ffo.....................',
      '.......+Ffoffo..................',
      '.......FFfo.ffo.................',
      '.......+Ffo..+fo................',
      '.......+Ffo..+fo.....+..........',
      '.......+Ffo..+fo.....+F.........',
      '.......+Ffo..+fo.....+Ffo.......',
      '........+Ffo.+fo.....+Ffo.......',
      '........FFfo.ffo.....FFfo.......',
      '........+Ffo.+fo.....+Ffo.......',
      '........+Ffo.+fo....+Ffo........',
      '........+Ffo.+o.....+Ffo........',
      '........+Ffo..+o....+Ffo........',
      '........+Ffo..+o....+Ffoffo.....',
      '........FFfo..f.....FFfo.ffo....',
      '.....offFFfo........+Ffo..+fo...',
      '....off.+Ffo........+Ffo..+fo...',
      '...off..+Ffo........+Ffo..+fo...',
      '..off...+Ffo........+Ffo..+fo...',
      '..off...+Ffo.......+Ffo...+fo...',
      '..off....FFfo......FFfo...ffo...',
      '..off....+Ffo......+Ffo...+fo...',
      '..off....+Ffo......+Ffo...+fo...',
      '..off....+Ffo......+Ffo...+fo...',
      '..off....+Ffo......+Ffo...+fo...',
      '..off....+Ffo......+Ffo...+fo...',
      '..off....FFfo......FFfo...fo....',
      '..off....+Ffo...offFFfo....+o...',
      '..off....+Ffo..off.+Ffo....+o...',
      '..off....+Ffofoff..+Ffo....+....',
      '...of....+Ffooffo..+Ffo.........',
      '..of....+Ffo.offfo.+Ffo.........',
      '..of....FFfo.offfoFFfo..........',
      '...+....+Ffo.offfoFFfo..........',
      '........+Ffo.offfoFFfo..........',
      '........+Ffo.offfoFFfo..........',
      '........+Ffo.offfoFFfo..........',
      '........+Ffo.offfoFFfo..........',
      '........FFfo.offfoFFfo..........',
      '........+Ffo..offoFFfo..........',
      '........+Ffo.offfoFFfo..........',
      '........+Ffo.offfoFFfoffo.......',
      '........+Ffo..+ffoFFfo.+fo......',
      '.....offFFfo...+o..+Ffo.+fo.....',
      '....off.FFfo....fo.FFfo.ffo.....',
      '...off.+Ffo.....+o.+Ffo.+fo.....',
      '..off..+Ffo.....+..+Ffo.+fo.....',
      '..off..+Ffo........+Ffo.+fo.....',
      '..off..+Ffo........+Ffo.+fo.....',
      '..off..+Ffo........+Ffo.+fo.....',
      '..off..FFfo........FFfo.ffo.....',
      '..off..+Ffo........+Ffo.+fo.....',
      '..off..+Ffo........+Ffo.+o......',
      '..off.+Ffo.........+Ffo..+o.....',
      '..off.+Ffo.........+Ffo..+o.....',
      '..off.+Ffo......offFFfo..+......',
      '...of.FFfo.....off.FFfo.........',
      '..of..+Ffoffo.off...+Ffo........',
      '..of..+Ffo.+foff....+Ffo........',
      '...+..+Ffo..+off....+Ffo........',
      '......+Ffo..+off....+Ffo........',
      '.....+Ffo...+off....+Ffo........',
      '.....FFfo...foff....FFfo........',
      '.....+Ffo...+off....+Ffo........',
      '.....+Ffo...+off....+Ffo........',
      '.....+Ffo...+fof.....+Ffo.......',
      '.....+Ffo...+of......+Ffo.......',
      '.....+Ffo...+of......+Ffo.......',
      '.....FFfo...fff......FFfo.......',
      '.....+Ffo...+o.......+Ffoffo....',
      '....+Ffo.....+o......+Ffo.+fo...',
      '.offFFfo.....+o......+Ffo..+fo..',
      'off.+Ffo.....+.......+Ffo..+fo..',
      'ff..+Ffo..............+Ffo.+fo.o',
      'f...FFfo..............FFfo.ffoof',
      'f...+Ffo..............+Ffo.+foof',
      'f...+Ffo..............+Ffo.+foof',
      'f...+Ffo..............+Ffo.+foof',
      'f...+Ffo..............+Ffo.+foof',
      'f...+Ffo..............+Ffo.+foof',
      'f...FFfo..............FFfo.ffoof',
      'f...+Ffo..............+Ffo.+foof',
      'f...+Ffo...............+Ffoffo.o',
      '...+Ffo.............offFFfoffoof',
      '...+Ffo............off.+Ffofo.of',
      '...+Ffoffo........off..+Ffo.+o.+'
    ]);
    /* --- END GENERATED ---------------------------------------- */

    /* ==========================================================
       B. THE ANIMALS. Eight of them, and every one is nameable
       from its black shape alone before any colour arrives: the
       clownfish's three bars, the parrotfish's blunt beak and
       high forehead, the mantis shrimp's stalked eyes and folded
       clubs, the moray's open jaw on a ribbon, the cuttlefish's
       fin skirt, the barracuda's needle, the lionfish's crown of
       banded spines, the manta's two great wings.
       Two frames each. All face LEFT; the sim flips them.
       ========================================================== */
    D('an_clown0', [
      '......oooooo....',
      '...oo&&WW&&&oo..',
      '..o&&%WW%&&&&&o.',
      '.o&Wp%WW%&&&&&&o',
      'o&%WW%WW%&&&&&&o',
      'o&%WW%WW%&&&&&&o',
      '.o&Wp%WW%&&&&&&o',
      '..o&&%WW%&&&&&o.',
      '...oo&&WW&&&oo..',
      '......oooooo....'
    ]);
    D('an_clown1', [
      '......oooooo....',
      '...oo&&WW&&&oo..',
      '..o&&%WW%&&&&&oo',
      '.o&Wp%WW%&&&&&&o',
      'o&%WW%WW%&&&&&%o',
      'o&%WW%WW%&&&&&&o',
      '.o&Wp%WW%&&&&&%o',
      '..o&&%WW%&&&&&oo',
      '...oo&&WW&&&oo..',
      '......oooooo....'
    ]);
    D('an_parrot0', [
      '.......oooooo.......',
      '.....ooFFFffFoo.....',
      '...ooFF++FFffFFoo...',
      '..oF++FFFFFffFFFFo..',
      '.oFWpFF++FFFffFFFFoo',
      'ocCFFFF++FFFffFFFFFo',
      'oCcoFFF++FFFffFFFFFo',
      'ocCFFFF++FFFffFFFFFo',
      '.oFFFFF++FFFffFFFFoo',
      '..oFFF++FFFffFFFFo..',
      '...ooFF++FFffFFoo...',
      '.....oo+FFffoo......',
      '.......oFffo........',
      '........oooo........'
    ]);
    D('an_parrot1', [
      '.......oooooo.......',
      '.....ooFFFffFoo.....',
      '...ooFF++FFffFFoo...',
      '..oF++FFFFFffFFFFoo.',
      '.oFWpFF++FFFffFFFFFo',
      'ocCFFFF++FFFffFFFFFo',
      'oCcoFFF++FFFffFFFFoo',
      'ocCFFFF++FFFffFFFFo.',
      '.oFFFFF++FFFffFFFFo.',
      '..oFFF++FFFffFFFFoo.',
      '...ooFF++FFffFFoo...',
      '.....oo+FFffoo......',
      '......oFffo.........',
      '......oooo..........'
    ]);
    D('an_mantis0', [
      'oWo.oWo...............',
      'o#o.o#o...............',
      '.oFo.oFo..............',
      '..oFFFFooooo..........',
      '.oF++FFFFFFFoo........',
      'oF++FFFFFFFFFFoo......',
      'oF+FFoFFoFFoFFFFoo..oo',
      'oFFFFoFFoFFoFFFFFFooFF',
      'oF&&FoFFoFFoFFFFFFooFF',
      'o&%%&ooooooooFFFFoo.oo',
      'o&%%&o...ooFFFFoo.....',
      '.o&&o......oooo.......',
      '..oo..................',
      '......................'
    ]);
    D('an_mantis1', [
      '.oWo.oWo..............',
      '.o#o.o#o..............',
      '..oFo.oFo.............',
      '...oFFFFooooo.........',
      '..oF++FFFFFFFoo.......',
      '.oF++FFFFFFFFFFoo...oo',
      '.oF+FFoFFoFFoFFFFooFFo',
      'oF&FFFoFFoFFoFFFFFFoFF',
      'o&%&FoFFoFFoFFFFFFooFF',
      'o&%%&ooooooooFFFFoo.oo',
      '.o&%&o...ooFFFFoo.....',
      '..o&&o.....oooo.......',
      '...oo.................',
      '......................'
    ]);
    D('an_moray0', [
      '..oooo........................',
      '.oWWWo........ooooooo.........',
      'oWWWWo....offFFFffFFffoo......',
      'oWpWWoooffFFFFFFFFFFFFffoo....',
      'oWWWoWWWWWWo+FFFFFFFFFFFFffo..',
      'oWWo.oooooo.oFFFFFFFFFFFFFFfo.',
      'oWWo........oFFFFFFFFFFFFFFFfo',
      'oWWWoWWWWWWo+FFFFFFFFFFFFFFfo.',
      'oWpWWoooffFFFFFFFFFFFFFFFFffo.',
      'oWWWWo....offFFFffFFffFFffoo..',
      '.oWWWo........ooooooooooo.....',
      '..oooo........................',
      '..............................',
      '..............................'
    ]);
    D('an_moray1', [
      '..oooo........................',
      '.oWWWo........................',
      'oWWWWo.......ooooooooo........',
      'oWpWWo....offFFFffFFffoo......',
      'oWWWWWWWo+FFFFFFFFFFFFFffo....',
      'oWWWWWWWo+FFFFFFFFFFFFFFFffo..',
      'oWWWWWWWo+FFFFFFFFFFFFFFFFFfo.',
      'oWpWWoooffFFFFFFFFFFFFFFFFFFfo',
      'oWWWWo....offFFFFFFFFFFFFFffo.',
      '.oWWWo........offFFFffFFffoo..',
      '..oooo............ooooooo.....',
      '..............................',
      '..............................',
      '..............................'
    ]);
    D('an_cuttle0', [
      '.....oooooo.....',
      '...ooZZAAaZzoo..',
      '..oZZAAaaaaZZzo.',
      '.oZAAaaaaaaaZZzo',
      'oZAWWoaaaaaaaZzo',
      'oZAWpWoaaaaaaZzo',
      'oZAWWoaaaaaaaZzo',
      '.oZAAaaaaaaaZZzo',
      '..oZZAAaaaaZZzo.',
      '..oxZoZaaZoZzo..',
      '.oxaxaoZZoazxzo.',
      'oxaxaxo..oxaxzo.',
      'oaxaxo....oaxzo.',
      'oxaxo......oxzo.',
      '.oao........oo..',
      '..o.............'
    ]);
    D('an_cuttle1', [
      '.....oooooo.....',
      '...ooZZAAaZzoo..',
      '..oZZAAaaaaZZzo.',
      '.oZAAaaaaaaaZZzo',
      'oZAWWoaaaaaaaZzo',
      'oZAWpWoaaaaaaZzo',
      'oZAWWoaaaaaaaZzo',
      '.oZAAaaaaaaaZZzo',
      '..oZZAAaaaaZZzo.',
      '...oxoZaaZoxo...',
      '..oxaoZZZZoazo..',
      '.oxaxo....oaxzo.',
      '.oxaxo....oaxzo.',
      '..oxo......ozo..',
      '..oo........oo..',
      '................'
    ]);
    D('an_cuda0', [
      '..o...........oooooo............',
      '.oWo.......oobbBBBBBbboo........',
      'oWpWoooobbBBBwwwwwwwBBBbboo.....',
      'oWWWWbbBBBwwwWWWWWWWwwwBBBbbo..o',
      'oWWWBBBwwwWWWWWWWWWWWWWwwwBBbboo',
      'oWWWBBBwwwWWWWWWWWWWWWWwwwBBbboo',
      'oWWWWbbBBBwwwWWWWWWWwwwBBBbbo..o',
      'oWpWoooobbBBBwwwwwwwBBBbboo.....',
      '.oWo.......oobbBBBBBbboo........',
      '..o...........oooooo............'
    ]);
    D('an_cuda1', [
      '..o...........oooooo........o...',
      '.oWo.......oobbBBBBBbboo...ooo..',
      'oWpWoooobbBBBwwwwwwwBBBbboobbo..',
      'oWWWWbbBBBwwwWWWWWWWwwwBBBbbBbo.',
      'oWWWBBBwwwWWWWWWWWWWWWWwwwBBbbo.',
      'oWWWBBBwwwWWWWWWWWWWWWWwwwBBbbo.',
      'oWWWWbbBBBwwwWWWWWWWwwwBBBbbBbo.',
      'oWpWoooobbBBBwwwwwwwBBBbboobbo..',
      '.oWo.......oobbBBBBBbboo...ooo..',
      '..o...........oooooo........o...'
    ]);
    D('an_lion0', [
      '..o...o...o...o.....',
      '.oWo.oWo.oWo.oWo....',
      '.o#o.o#o.o#o.o#o....',
      '.oWo.oWo.oWo.oWo....',
      '.o#o.o#o.o#o.o#o....',
      '..oo..oo..oo..oo....',
      '...ooooooooooooo....',
      '..o#WW##WW##WW#oo...',
      '.oWW####WW##WW##Wo..',
      'o#WWpW##WW##WW###Woo',
      'o#WW##W#WW##WW####Wo',
      'o#WWpW##WW##WW###Woo',
      '.oWW####WW##WW##Wo..',
      '..o#WW##WW##WW#oo...',
      '...ooooooooooooo....',
      '..oo..oo..oo..oo....',
      '.o#o.o#o.o#o.o#o....',
      '.ooo.ooo.ooo.ooo....'
    ]);
    D('an_lion1', [
      '..o...o...o...o.....',
      '.oWo.oWo.oWo.oWo....',
      '.o#o.o#o.o#o.o#o....',
      '.oWo.oWo.oWo.oWo....',
      '.o#o.o#o.o#o.o#o....',
      '..oo..oo..oo..oo....',
      '...ooooooooooooo....',
      '..o#WW##WW##WW#oo...',
      '.oWW####WW##WW##Woo.',
      'o#WWpW##WW##WW###WWo',
      'o#WW##W#WW##WW####Wo',
      'o#WWpW##WW##WW###WWo',
      '.oWW####WW##WW##Woo.',
      '..o#WW##WW##WW#oo...',
      '...ooooooooooooo....',
      '...oo..oo..oo..oo...',
      '...o#o.o#o.o#o.o#o..',
      '...ooo.ooo.ooo.ooo..'
    ]);
    D('an_manta0', [
      '.........oo.....oo..........................',
      '........oddo...oddo.........................',
      '.......oiddDDDDDddio........................',
      '.....ooiddDDDeeeDDddioo.....................',
      '..oooiddDDDeeeEEeeeDDddiooo.................',
      'ooiddDDDDeeeEEEEEEeeeDDDDddioo..............',
      'oiddDDDeeeEEEEEEEEEEEEeeeDDDddio............',
      'oidDDeeeEEEEEEEEEEEEEEEEEeeeDDdio...........',
      'oidDeeeEEEEEEEEEEEEEEEEEEEEEeeDdio..oo......',
      'oidDeeeEEEEEEEEEEEEEEEEEEEEEeeDdio.oddo.....',
      '.oidDeeeEEEEEEEEEEEEEEEEEEEeeDdio.oddo......',
      '..oidDDeeeEEEEEEEEEEEEEEEeeDDdio.oddo.......',
      '...ooidDDeeeEEEEEEEEEEEeeDDdiooodddo........',
      '.....ooidDDeeeEEEEEEEeeDDdioodddoo..........',
      '.......ooidDDeeeEEEeeDDdioodddo.............',
      '.........ooidDDeeeeeDDdiodddo...............',
      '...........ooidDDDDDDdiddo..................',
      '.............ooidddddiddo...................',
      '...............oooooooo.....................',
      '............................................'
    ]);
    D('an_manta1', [
      '.........oo.....oo..........................',
      '........oddo...oddo.........................',
      '.......oiddDDDDDddio........................',
      '......oiddDDDeeeDDddio......................',
      '....ooiddDDDeeeEEeeeDDddioo.................',
      '..ooiddDDDDeeeEEEEEEeeeDDDDddioo............',
      'ooiddDDDeeeEEEEEEEEEEEEeeeDDDddioo..........',
      'oidDDeeeEEEEEEEEEEEEEEEEEeeeDDdio...........',
      'oidDeeeEEEEEEEEEEEEEEEEEEEEEeeDdio..........',
      'oidDeeeEEEEEEEEEEEEEEEEEEEEEeeDdio....oo....',
      'oidDeeeEEEEEEEEEEEEEEEEEEEEEeeDdio...oddo...',
      '.oidDDeeeEEEEEEEEEEEEEEEEEeeDDdio...oddo....',
      '..ooidDDeeeEEEEEEEEEEEEEeeDDdio....oddo.....',
      '....ooidDDeeeEEEEEEEEEeeDDdio....oddo.......',
      '......ooidDDeeeEEEEEeeDDdio....oddo.........',
      '........ooidDDeeeEEeeDDdio...oddo...........',
      '..........ooidDDeeeDDdio...oddo.............',
      '............ooidDDDDdio..oddo...............',
      '..............oooooooo...oo.................',
      '............................................'
    ]);

    P.anim('an_clown', ['an_clown0', 'an_clown1'], 7);
    P.anim('an_parrot', ['an_parrot0', 'an_parrot1'], 5);
    P.anim('an_mantis', ['an_mantis0', 'an_mantis1'], 6);
    P.anim('an_moray', ['an_moray0', 'an_moray1'], 4);
    P.anim('an_cuttle', ['an_cuttle0', 'an_cuttle1'], 5);
    P.anim('an_cuda', ['an_cuda0', 'an_cuda1'], 8);
    P.anim('an_lion', ['an_lion0', 'an_lion1'], 3);
    P.anim('an_manta', ['an_manta0', 'an_manta1'], 3);
  }

  return { build };
})();
